### ISSUE TITLE
Willow feedback - wheelies are cool, but acceleration smoothing!

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#111]
They mentioned that it was doing wheelies. This could be either the toppling issue...but more likely I think it is due to the control effect when you send a command to the robot after it's been idle. I noticed this at roscon.

I can send a command of only 7cm/s (very slow), but in the first 0.5secs, the robot tries to launch into space (really high torque). Then it drops back to really low torque and speed. Is this a firmware issue? Possibly due to high P gains?

**Comment by jakan2** [comment]
A kubuki has slightly larger gain than iclebo arte. 
But i am wandering that it has high speed initially. In the case of iclebo arte, its motion is smoother.
I will get the some data then compare with iclebo arte.

**Comment by yhju** [comment]
To avoid these uncomfortable behavior, we can add 'high acceleration smoothing' feature in the middle of kobuki_driver package. And by using some parameters(or dynamic_reconfigure? or services?), user can selectively disable/enable it.

**Comment by stonier** [comment]
Disable/enable doesn't need to be dynamic reconfigure or ros api'd. I imagine users will either want it on or off, not changeable in the runtime.

**Comment by yhju** [comment]
Implemented and tested with ad906f0a6ebeb732afb5938f79200f8eb4bccabf
Done.
