### ISSUE TITLE
Led command warning with beep

### ISSUE THREAD

**Issue by yhju** [yujinrobot/kobuki#114]
it will be awesome

**Comment by bit-pirate** [comment]
it's gonna be legend ...

**Comment by bit-pirate** [comment]
wait for it

**Comment by bit-pirate** [comment]
dary!

**Comment by bit-pirate** [comment]
:-)

**Comment by stonier** [comment]
Perhaps just reimplement led's without a confusing array. i.e. just led1 and led2 variables. If we need arrays in the future, worry about it then.

**Comment by stonier** [comment]
Make sure kobuki_node/src/test/test_led_array.py is updated and working.

**Comment by yhju** [comment]
Implemented and tested.
Done.
