### ISSUE TITLE
Digital output flipped

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#115]
I don't know if this is in hardware or firmware but the digital output leds on the test board are lit up when false, not lit up when true.

**Comment by stonier** [comment]
Looks like it is hardware - for some reason they turn led's on by default at 0? 

It's a hardware thing. Talk to Hyeong-Ju about doing this differently in the future (principle of least surprise).

**Comment by jakan2** [comment]
What i understand is that it supply high if user set the 1 for particular point of digital output.
Reason why we confused is led is turns on when it get the zero voltage not high voltage by its circuitry.

_Can we close this one????_

**Comment by stonier** [comment]
Young Hoon, did you confirm the voltage levels?

**Comment by yhju** [comment]
Digital output are not flipped. There were some confusing. When it set true, digital output will be high voltage. But exact level of high voltage is depends on user's circuitry implementation, not specified by default.
