### ISSUE TITLE
Serial comms port

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#117]
Can firmware automatically redirect output here? Important for people like national instruments who will be putting a vxworks board on top.

**Comment by jakan2** [comment]
_What kind of output?_
- Is that just serial output?
- Is that control output (motor)?

**Comment by stonier** [comment]
All the output - instead of sending it to the serial port with the ftdi chip, send it to the last serial port where the data can be caught on the big pin port. Then the national instruments guys can write their own vxworks driver to convert the kobuki protocol to what they need.

Is this the right thinking?

**Comment by stonier** [comment]
Put this on the todo until we actually have a need.

**Comment by stonier** [comment]
Young Hoon, is this finished now?

**Comment by yhju** [comment]
Yes, serial port in 25-pin connector is works now.

**Comment by stonier** [comment]
Can you add a tutorial on the kobuki website hardware section?

**Comment by yhju** [comment]
Added on kobuki website; http://kobuki.yujinrobot.com/documentation/hardware/serial-port/
Done.
