### ISSUE TITLE
Fuerte kinect support

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#119]
Doesn't work...flamin hell! What a time to find out.

**Comment by stonier** [comment]
Can use openni_camera_depracated. But we need to upgrade to use openni_camera. I've started work on modifying the launcher, but will need some testing.

**Comment by corot** [comment]
In fact, openni_camera_depracated doesn't work properly in fuerte/preciese. I have fixed it installing the unstable debs of openni. I'll try to complete the migration to fuerte asap.

**Comment by corot** [comment]
I did it for topseung, and will do the same for kobuki

**Comment by corot** [comment]
The openni_launch package also publish kinect "internal" tfs, so I have removed them from the xacro file. I suppose this fix the issue with the kinect frames: the new ones are slightly displaced in relation to the old ones, but I haven't verified if the difference is the same that Younghun noticed.
