### ISSUE TITLE
Battery Documentation

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#129]
Need the following done:
- [Roswiki Tutorial](http://ros.org/wiki/kobuki/Tutorials) for generating a battery graph with kobuki turtlebot. It should reference our graphs back on rnd.yujinrobot.com
- [Move Battery Swap Tutorial](http://ros.org/wiki/kobuki/Tutorials/Battery%20Bombastics) to our website [HowTos](http://kobuki.yujinrobot.com/index.php/support/howtos/). Leave the tutorial on the roswiki pointing to our website howto.

**Comment by corot** [comment]
Did it. It would be interesting to provide matlab scripts also?

**Comment by stonier** [comment]
I think its fine as is. When I was teaching I found showing too many methods in simple tutorials actually just confuses students. 

Could use a screenshot of the rxbag plot though.

**Comment by corot** [comment]
네!

2012/6/12 Daniel Stonier
reply@reply.github.com:
