### ISSUE TITLE
Kinect Location & Poles

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#130]
- Confirm (turtlebot sig) what the status is with the slight turtlebot urdf location error.
- Confirm that our poles are not in the kinect field of view.

**Comment by corot** [comment]
In the Mk II are not in the 3D sensor fov. In the RGB you can see a very thin line of the upper plate in the left side because the kinect and the plate are not perfectly aligned

**Comment by stonier** [comment]
Need to corroborate with young hoon on this - he got images showing the problem being fairly significant.

What is the status on moving the poles young hoon?

**Comment by yhju** [comment]
I am working with DK. He will assemble a new pole and plate today.
Anyway, for the detailed information with picture, just check the issue #1954 on redmine.

**Comment by stonier** [comment]
Redmine issue: http://redmine.yujin.com/issues/1954

Still waiting on willow about the urdf location error - tully has replied and they'll investigate.

**Comment by stonier** [comment]
Latest stacks and poles are ok.

Urdf error I'm re-raising in turtlebot/turtlebot/issues/9
