### ISSUE TITLE
digital input events?

### ISSUE THREAD

**Issue by yhju** [yujinrobot/kobuki#135]

**Comment by stonier** [comment]
Put these under a publisher in xxx/events so that a user doesn't have to listen and parse the core sensor publisher at high frequencies.

**Comment by corot** [comment]
I'll also create wheel drop and cliff events;  cannot see a reason to
have bumpers as the only sensor that trigger events

2012/6/21 Daniel Stonier
reply@reply.github.com:

**Comment by corot** [comment]
Should we raise other events?
- adapter plug/unplug
- robot stalled (can be inferred comparing motor current and current velocity)

**Comment by stonier** [comment]
Adapter is probably a useful one. Or more generally - charging.

Stalled - we could do, is it something you use alot?
