### ISSUE TITLE
Battery charge set to 100% just after connecting it to the adapter

### ISSUE THREAD

**Issue by corot** [yujinrobot/kobuki#137]
This happens because the robot signals "charged" for about a second just after connecting it, and then switches to the correct state of "charging"

**Comment by corot** [comment]
After talking with cheyong, we have decided to postpone this. He will fix in the controller, what will be cleaner that a hack in the driver.

**Comment by stonier** [comment]
Sounds good.

**Comment by jakan2** [comment]
It's fixed now
