### ISSUE TITLE
How to load a static (i.e. bitmap) map in the maps database?

### ISSUE THREAD

**Issue by corot** [yujinrobot/kobuki#138]
Now we do the inverse operation: create a map with kobuki android make_a_make app, and export it from the mongo database to a bitmap and metadata yaml file.

But we cannot provide our previous maps on map_store, what forces us to re-create maps that we already have to use them with kobuki android map_nav app.

**Comment by stonier** [comment]
no services provided by the map_store node?

**Comment by corot** [comment]
Yes,  add_map.py

But I'll write a short tutorial with all the steps: launch database,
load and publish map, launch map_store and call add_map

2012/6/20 Daniel Stonier
reply@reply.github.com:

**Comment by corot** [comment]
mmm... turned to be much easier with the add_map.launch script. Anyway, I added a short howto in redmine.
