### ISSUE TITLE
Vibration at low speed commands

### ISSUE THREAD

**Issue by yhju** [yujinrobot/kobuki#144]
Rotation velocity vibrate periodically at low speed(0.33 rad/s).
But, it is relatively stable at 0.66 rad/s or higher.

**Comment by yhju** [comment]
See Also: Redmine Issue [#2083](http://redmine.yujin.com/issues/2083). Please check that as it has Young Hoon's test result plots.

**Comment by jakan2** [comment]
It looks wheel velocity control problem.
When i take I -term out from the controller. 
Robot does not look vibrator

**Comment by bit-pirate** [comment]
헐! Since when does our robot look like a vibrator!?

**Comment by stonier** [comment]
Some other issues, probably concerning the same topic. It has problems overcoming the friction at low rotational velocities. Just not enough grunt going in when the p-error increases for low speeds.

Some videos for you einstein:

https://plus.google.com/photos/116045912110987101704/albums/5819857120371331537?authkey=CPuy_rnV-pv_CA

**Comment by stonier** [comment]
Note that they're having problems on concrete (surprising since we had most problems on carpet). Test results on that.

**Comment by stonier** [comment]
If we can improve things by wednesday, that would be great.

**Comment by tfoote** [comment]
We added some teflon tape to the passive wheels and we experienced much better performance.  https://plus.google.com/photos/116045912110987101704/albums/5820093395314527649?authkey=CIjjrsHC-rvs2gE

There are pictures of the taped wheels and a video of the robot turning better with the taped wheels.

**Comment by stonier** [comment]
Updated the name for this one to hopefully better isolate the friction and the low speed control issues.

I was observing the vibration (overshot, undershoot) issue this morning commanding a linear 5cm/s speed. This will have nothing to do with the friction issues.

**Comment by corot** [comment]
This gets mostly solved with firmware version 1.1.3.
