### ISSUE TITLE
Check for cross platform support of kobuki_driver

### ISSUE THREAD

**Issue by yhju** [yujinrobot/kobuki#149]
At least on Windows.

**Comment by stonier** [comment]
11월초. 

Waiting for groovy catkin freeze and big winros update.

재영 also waiting for catkinized ecl to do cross compiles.

**Comment by yhju** [comment]
What I mean is cross platform compatibility of just `kobuki_driver` package for non-ROS or embedded applications.
But **turtlebot** with **winros** is also preferable.

**Comment by stonier** [comment]
Turtlebot has no relevance.

I need groovy catkin to cross-compile or msvc-compile (via winros) both ecl and kobuki_driver packages.

**Comment by stonier** [comment]
Opening separate issues.
