### ISSUE TITLE
Kobuki node: Fixed hard-coded joint names

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/kobuki#152]
In the parameter file for the mobile base aka kobuki node one can set names for the wheels.
But kobuki_node.cpp looks like they are hardcoded.
Please fix!

**Comment by stonier** [comment]
How else would you do this marcus?

I don't see any way to get the xacro link names directly from there into the cpp code.

**Comment by bit-pirate** [comment]
Using the parameter server. Since we already have a yaml in place, I assumed, this was the idea from the start, but nobody actually implemented it.

Retrieving this information directly from the URDF would be nice, but also more complex. It probably would require some naming standardisation. I think, using the param server is good enough.

**Comment by corot** [comment]
By now just use the parameter server. When we have time, we should take a look to how joint_states_publisher analyzes the robot description to take joint names.

Btw, I have also removed caster wheel joints, who have no state to publish.

**Comment by stonier** [comment]
Problem is back - TF's aren't getting found for the wheels.

**Comment by stonier** [comment]
My bad, when viewing just the model, you need the joint state publisher.
