### ISSUE TITLE
Apps for roboworld

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#158]
- Web app
  - Panorama interface
  - Frontend for calling the robot 'calling' see below.
- Side script that tells the robot to go forward until obstacle is detected in front (similar to follower), 'Calling'
- Side script that continuously runs the panoram app

**Comment by jihoonl** [comment]
Panorama interface(DONE)
Side script that continuously runs the panoram app (DONE)

next : calling

**Comment by jihoonl** [comment]
App manager web version(done)
Teleop interface(DONE)
