### ISSUE TITLE
kobuki_comms to kobuki_msgs

### ISSUE THREAD

**Issue by jihoonl** [yujinrobot/kobuki#161]

**Comment by jihoonl** [comment]
jihoonl@whoolala:~/ttt$ cfind kobuki_comms
./kobuki/kobuki_node/src/node/kobuki_node.cpp:42:#include <kobuki_comms/VersionInfo.h>
./kobuki/kobuki_node/src/node/kobuki_node.cpp:318:  version_info_publisher = nh.advertise < kobuki_comms::VersionInfo > ("version_info",  100, true); // latched publisher
./kobuki/kobuki_node/src/node/kobuki_node.cpp:319:  button_event_publisher = nh.advertise < kobuki_comms::ButtonEvent > ("events/button", 100);
./kobuki/kobuki_node/src/node/kobuki_node.cpp:320:  bumper_event_publisher = nh.advertise < kobuki_comms::BumperEvent > ("events/bumper", 100);
./kobuki/kobuki_node/src/node/kobuki_node.cpp:321:  cliff_event_publisher  = nh.advertise < kobuki_comms::CliffEvent >  ("events/cliff",  100);
./kobuki/kobuki_node/src/node/kobuki_node.cpp:322:  wheel_event_publisher  = nh.advertise < kobuki_comms::WheelDropEvent > ("events/wheel_drop", 100);
./kobuki/kobuki_node/src/node/kobuki_node.cpp:323:  power_event_publisher  = nh.advertise < kobuki_comms::PowerSystemEvent > ("events/power_system", 100);
./kobuki/kobuki_node/src/node/kobuki_node.cpp:324:  input_event_publisher  = nh.advertise < kobuki_comms::DigitalInputEvent > ("events/digital_input", 100);
./kobuki/kobuki_node/src/node/kobuki_node.cpp:325:  robot_event_publisher  = nh.advertise < kobuki_comms::RobotStateEvent > ("events/robot_state", 100, true); // also latched
./kobuki/kobuki_node/src/node/kobuki_node.cpp:326:  sensor_state_publisher = nh.advertise < kobuki_comms::SensorState > ("sensors/core", 100);
./kobuki/kobuki_node/src/node/kobuki_node.cpp:327:  dock_ir_publisher = nh.advertise < kobuki_comms::DockInfraRed > ("sensors/dock_ir", 100);
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:65:      kobuki_comms::SensorState state;
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:169:      kobuki_comms::DockInfraRed msg;
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:196:    kobuki_comms::VersionInfo msg;
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:212:    kobuki_comms::ButtonEvent msg;
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:214:      case(ButtonEvent::Pressed) : { msg.state = kobuki_comms::ButtonEvent::PRESSED; break; }
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:215:      case(ButtonEvent::Released) : { msg.state = kobuki_comms::ButtonEvent::RELEASED; break; }
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:219:      case(ButtonEvent::Button0) : { msg.button = kobuki_comms::ButtonEvent::Button0; break; }
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:220:      case(ButtonEvent::Button1) : { msg.button = kobuki_comms::ButtonEvent::Button1; break; }
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:221:      case(ButtonEvent::Button2) : { msg.button = kobuki_comms::ButtonEvent::Button2; break; }
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:232:    kobuki_comms::BumperEvent msg;
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:234:      case(BumperEvent::Pressed) : { msg.state = kobuki_comms::BumperEvent::PRESSED; break; }
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:235:      case(BumperEvent::Released) : { msg.state = kobuki_comms::BumperEvent::RELEASED; break; }
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:239:      case(BumperEvent::Left) : { msg.bumper = kobuki_comms::BumperEvent::LEFT; break; }
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:240:      case(BumperEvent::Center) : { msg.bumper = kobuki_comms::BumperEvent::CENTER; break; }
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:241:      case(BumperEvent::Right) : { msg.bumper = kobuki_comms::BumperEvent::RIGHT; break; }
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:252:    kobuki_comms::CliffEvent msg;
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:254:      case(CliffEvent::Floor) : { msg.state = kobuki_comms::CliffEvent::FLOOR; break; }
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:255:      case(CliffEvent::Cliff) : { msg.state = kobuki_comms::CliffEvent::CLIFF; break; }
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:259:      case(CliffEvent::Left)   : { msg.sensor = kobuki_comms::CliffEvent::LEFT;   break; }
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:260:      case(CliffEvent::Center) : { msg.sensor = kobuki_comms::CliffEvent::CENTER; break; }
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:261:      case(CliffEvent::Right)  : { msg.sensor = kobuki_comms::CliffEvent::RIGHT;  break; }
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:273:    kobuki_comms::WheelDropEvent msg;
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:275:      case(WheelEvent::Dropped) : { msg.state = kobuki_comms::WheelDropEvent::DROPPED; break; }
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:276:      case(WheelEvent::Raised)  : { msg.state = kobuki_comms::WheelDropEvent::RAISED;  break; }
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:280:      case(WheelEvent::Left)  : { msg.wheel = kobuki_comms::WheelDropEvent::LEFT;  break; }
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:281:      case(WheelEvent::Right) : { msg.wheel = kobuki_comms::WheelDropEvent::RIGHT; break; }
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:292:    kobuki_comms::PowerSystemEvent msg;
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:295:        { msg.event = kobuki_comms::PowerSystemEvent::UNPLUGGED; break; }
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:297:        { msg.event = kobuki_comms::PowerSystemEvent::PLUGGED_TO_ADAPTER;  break; }
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:299:        { msg.event = kobuki_comms::PowerSystemEvent::PLUGGED_TO_DOCKBASE; break; }
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:301:        { msg.event = kobuki_comms::PowerSystemEvent::CHARGE_COMPLETED;  break; }
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:303:        { msg.event = kobuki_comms::PowerSystemEvent::BATTERY_LOW; break; }
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:305:        { msg.event = kobuki_comms::PowerSystemEvent::BATTERY_CRITICAL;  break; }
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:316:    kobuki_comms::DigitalInputEvent msg;
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:327:    kobuki_comms::RobotStateEvent msg;
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:329:      case(RobotEvent::Online)  : { msg.state = kobuki_comms::RobotStateEvent::ONLINE;  break; }
./kobuki/kobuki_node/src/node/slot_callbacks.cpp:330:      case(RobotEvent::Offline) : { msg.state = kobuki_comms::RobotStateEvent::OFFLINE; break; }
./kobuki/kobuki_node/src/node/subscriber_callbacks.cpp:70:void KobukiNode::subscribeLed1Command(const kobuki_comms::LedConstPtr msg)
./kobuki/kobuki_node/src/node/subscriber_callbacks.cpp:73:  case kobuki_comms::Led::GREEN:  kobuki.setLed(Led1, Green ); break;
./kobuki/kobuki_node/src/node/subscriber_callbacks.cpp:74:  case kobuki_comms::Led::ORANGE: kobuki.setLed(Led1, Orange ); break; 
./kobuki/kobuki_node/src/node/subscriber_callbacks.cpp:75:  case kobuki_comms::Led::RED:    kobuki.setLed(Led1, Red ); break;
./kobuki/kobuki_node/src/node/subscriber_callbacks.cpp:76:  case kobuki_comms::Led::BLACK:  kobuki.setLed(Led1, Black ); break;
./kobuki/kobuki_node/src/node/subscriber_callbacks.cpp:82:void KobukiNode::subscribeLed2Command(const kobuki_comms::LedConstPtr msg)
./kobuki/kobuki_node/src/node/subscriber_callbacks.cpp:85:  case kobuki_comms::Led::GREEN:  kobuki.setLed(Led2, Green ); break;
./kobuki/kobuki_node/src/node/subscriber_callbacks.cpp:86:  case kobuki_comms::Led::ORANGE: kobuki.setLed(Led2, Orange ); break;
./kobuki/kobuki_node/src/node/subscriber_callbacks.cpp:87:  case kobuki_comms::Led::RED:    kobuki.setLed(Led2, Red ); break;
./kobuki/kobuki_node/src/node/subscriber_callbacks.cpp:88:  case kobuki_comms::Led::BLACK:  kobuki.setLed(Led2, Black ); break;
./kobuki/kobuki_node/src/node/subscriber_callbacks.cpp:94:void KobukiNode::subscribeDigitalOutputCommand(const kobuki_comms::DigitalOutputConstPtr msg)
./kobuki/kobuki_node/src/node/subscriber_callbacks.cpp:105:void KobukiNode::subscribeExternalPowerCommand(const kobuki_comms::DigitalOutputConstPtr msg)
./kobuki/kobuki_node/src/node/subscriber_callbacks.cpp:119:void KobukiNode::subscribeSoundCommand(const kobuki_comms::SoundConstPtr msg)
./kobuki/kobuki_node/src/node/subscriber_callbacks.cpp:121:  if ( msg->value == kobuki_comms::Sound::ON )
./kobuki/kobuki_node/src/node/subscriber_callbacks.cpp:125:  else if ( msg->value == kobuki_comms::Sound::OFF )
./kobuki/kobuki_node/src/node/subscriber_callbacks.cpp:129:  else if ( msg->value == kobuki_comms::Sound::RECHARGE )
./kobuki/kobuki_node/src/node/subscriber_callbacks.cpp:133:  else if ( msg->value == kobuki_comms::Sound::BUTTON )
./kobuki/kobuki_node/src/node/subscriber_callbacks.cpp:137:  else if ( msg->value == kobuki_comms::Sound::ERROR )
./kobuki/kobuki_node/src/node/subscriber_callbacks.cpp:141:  else if ( msg->value == kobuki_comms::Sound::CLEANINGSTART )
./kobuki/kobuki_node/src/node/subscriber_callbacks.cpp:145:  else if ( msg->value == kobuki_comms::Sound::CLEANINGEND )
./kobuki/kobuki_node/manifest.xml:26:  <depend package="kobuki_comms"/>
./kobuki/kobuki_node/include/kobuki_node/kobuki_node.hpp:59:#include <kobuki_comms/ButtonEvent.h>
./kobuki/kobuki_node/include/kobuki_node/kobuki_node.hpp:60:#include <kobuki_comms/BumperEvent.h>
./kobuki/kobuki_node/include/kobuki_node/kobuki_node.hpp:61:#include <kobuki_comms/CliffEvent.h>
./kobuki/kobuki_node/include/kobuki_node/kobuki_node.hpp:62:#include <kobuki_comms/WheelDropEvent.h>
./kobuki/kobuki_node/include/kobuki_node/kobuki_node.hpp:63:#include <kobuki_comms/PowerSystemEvent.h>
./kobuki/kobuki_node/include/kobuki_node/kobuki_node.hpp:64:#include <kobuki_comms/DigitalInputEvent.h>
./kobuki/kobuki_node/include/kobuki_node/kobuki_node.hpp:65:#include <kobuki_comms/RobotStateEvent.h>
./kobuki/kobuki_node/include/kobuki_node/kobuki_node.hpp:66:#include <kobuki_comms/DigitalOutput.h>
./kobuki/kobuki_node/include/kobuki_node/kobuki_node.hpp:67:#include <kobuki_comms/Led.h>
./kobuki/kobuki_node/include/kobuki_node/kobuki_node.hpp:68:#include <kobuki_comms/SensorState.h>
./kobuki/kobuki_node/include/kobuki_node/kobuki_node.hpp:69:#include <kobuki_comms/DockInfraRed.h>
./kobuki/kobuki_node/include/kobuki_node/kobuki_node.hpp:70:#include <kobuki_comms/Sound.h>
./kobuki/kobuki_node/include/kobuki_node/kobuki_node.hpp:71:#include <kobuki_comms/VersionInfo.h>
./kobuki/kobuki_node/include/kobuki_node/kobuki_node.hpp:124:  void subscribeLed1Command(const kobuki_comms::LedConstPtr);
./kobuki/kobuki_node/include/kobuki_node/kobuki_node.hpp:125:  void subscribeLed2Command(const kobuki_comms::LedConstPtr);
./kobuki/kobuki_node/include/kobuki_node/kobuki_node.hpp:126:  void subscribeDigitalOutputCommand(const kobuki_comms::DigitalOutputConstPtr);
./kobuki/kobuki_node/include/kobuki_node/kobuki_node.hpp:127:  void subscribeExternalPowerCommand(const kobuki_comms::DigitalOutputConstPtr);
./kobuki/kobuki_node/include/kobuki_node/kobuki_node.hpp:129:  void subscribeSoundCommand(const kobuki_comms::SoundConstPtr);
./kobuki/kobuki_factory_test/src/qnode.cpp:21:#include <kobuki_comms/Led.h>
./kobuki/kobuki_factory_test/src/qnode.cpp:22:#include <kobuki_comms/Sound.h>
./kobuki/kobuki_factory_test/src/qnode.cpp:23:#include <kobuki_comms/DigitalOutput.h>
./kobuki/kobuki_factory_test/src/qnode.cpp:83:void QNode::versionInfoCB(const kobuki_comms::VersionInfo::ConstPtr& msg) {
./kobuki/kobuki_factory_test/src/qnode.cpp:95:void QNode::sensorsCoreCB(const kobuki_comms::SensorState::ConstPtr& msg) {
./kobuki/kobuki_factory_test/src/qnode.cpp:120:void QNode::dockBeaconCB(const kobuki_comms::DockInfraRed::ConstPtr& msg) {
./kobuki/kobuki_factory_test/src/qnode.cpp:155:void QNode::buttonEventCB(const kobuki_comms::ButtonEvent::ConstPtr& msg) {
./kobuki/kobuki_factory_test/src/qnode.cpp:161:      (msg->state  == kobuki_comms::ButtonEvent::PRESSED)) {
./kobuki/kobuki_factory_test/src/qnode.cpp:164:    if ((msg->button == kobuki_comms::ButtonEvent::Button0) ||
./kobuki/kobuki_factory_test/src/qnode.cpp:165:        (msg->button == kobuki_comms::ButtonEvent::Button2)) {
./kobuki/kobuki_factory_test/src/qnode.cpp:167:        under_test->device_ok[Robot::LED_1] = msg->button == kobuki_comms::ButtonEvent::Button0;
./kobuki/kobuki_factory_test/src/qnode.cpp:168:        under_test->device_ok[Robot::LED_2] = msg->button == kobuki_comms::ButtonEvent::Button0;
./kobuki/kobuki_factory_test/src/qnode.cpp:171:        under_test->device_ok[Robot::SOUNDS] = msg->button == kobuki_comms::ButtonEvent::Button0;
./kobuki/kobuki_factory_test/src/qnode.cpp:174:        under_test->device_ok[Robot::D_INPUT] = msg->button == kobuki_comms::ButtonEvent::Button0;
./kobuki/kobuki_factory_test/src/qnode.cpp:175:        under_test->device_ok[Robot::D_OUTPUT] = msg->button == kobuki_comms::ButtonEvent::Button0;
./kobuki/kobuki_factory_test/src/qnode.cpp:178:      if (msg->button == kobuki_comms::ButtonEvent::Button0)
./kobuki/kobuki_factory_test/src/qnode.cpp:180:      else if (msg->button == kobuki_comms::ButtonEvent::Button2)
./kobuki/kobuki_factory_test/src/qnode.cpp:209:    if (msg->state == kobuki_comms::ButtonEvent::RELEASED)
./kobuki/kobuki_factory_test/src/qnode.cpp:221:void QNode::bumperEventCB(const kobuki_comms::BumperEvent::ConstPtr& msg) {
./kobuki/kobuki_factory_test/src/qnode.cpp:239:    if (msg->state == kobuki_comms::BumperEvent::PRESSED) {
./kobuki/kobuki_factory_test/src/qnode.cpp:255:void QNode::wDropEventCB(const kobuki_comms::WheelDropEvent::ConstPtr& msg) {
./kobuki/kobuki_factory_test/src/qnode.cpp:260:      (msg->wheel == kobuki_comms::WheelDropEvent::LEFT)?Robot::W_DROP_L:Robot::W_DROP_R;
./kobuki/kobuki_factory_test/src/qnode.cpp:264:  if (((msg->state == kobuki_comms::WheelDropEvent::DROPPED) &&
./kobuki/kobuki_factory_test/src/qnode.cpp:266:      ((msg->state == kobuki_comms::WheelDropEvent::RAISED) &&
./kobuki/kobuki_factory_test/src/qnode.cpp:284:void QNode::cliffEventCB(const kobuki_comms::CliffEvent::ConstPtr& msg) {
./kobuki/kobuki_factory_test/src/qnode.cpp:288:  Robot::Device dev = (msg->sensor == kobuki_comms::CliffEvent::LEFT) ?Robot::CLIFF_L:
./kobuki/kobuki_factory_test/src/qnode.cpp:289:                      (msg->sensor == kobuki_comms::CliffEvent::RIGHT)?Robot::CLIFF_R:
./kobuki/kobuki_factory_test/src/qnode.cpp:294:  if (((msg->state == kobuki_comms::CliffEvent::CLIFF) &&
./kobuki/kobuki_factory_test/src/qnode.cpp:296:      ((msg->state == kobuki_comms::CliffEvent::FLOOR) &&
./kobuki/kobuki_factory_test/src/qnode.cpp:317:void QNode::powerEventCB(const kobuki_comms::PowerSystemEvent::ConstPtr& msg) {
./kobuki/kobuki_factory_test/src/qnode.cpp:324:    if ((msg->event != kobuki_comms::PowerSystemEvent::CHARGE_COMPLETED) &&
./kobuki/kobuki_factory_test/src/qnode.cpp:325:        (msg->event != kobuki_comms::PowerSystemEvent::BATTERY_LOW)      &&
./kobuki/kobuki_factory_test/src/qnode.cpp:326:        (msg->event != kobuki_comms::PowerSystemEvent::BATTERY_CRITICAL))
./kobuki/kobuki_factory_test/src/qnode.cpp:336:#define PTAE kobuki_comms::PowerSystemEvent::PLUGGED_TO_ADAPTER
./kobuki/kobuki_factory_test/src/qnode.cpp:337:#define PTDE kobuki_comms::PowerSystemEvent::PLUGGED_TO_DOCKBASE
./kobuki/kobuki_factory_test/src/qnode.cpp:342:      ((msg->event == kobuki_comms::PowerSystemEvent::UNPLUGGED) &&
./kobuki/kobuki_factory_test/src/qnode.cpp:359:void QNode::inputEventCB(const kobuki_comms::DigitalInputEvent::ConstPtr& msg) {
./kobuki/kobuki_factory_test/src/qnode.cpp:375:      kobuki_comms::DigitalOutput cmd;
./kobuki/kobuki_factory_test/src/qnode.cpp:383:  kobuki_comms::DigitalOutput cmd;
./kobuki/kobuki_factory_test/src/qnode.cpp:433:void QNode::robotEventCB(const kobuki_comms::RobotStateEvent::ConstPtr& msg) {
./kobuki/kobuki_factory_test/src/qnode.cpp:434:  if (msg->state == kobuki_comms::RobotStateEvent::ONLINE) {
./kobuki/kobuki_factory_test/src/qnode.cpp:453:  else if (msg->state == kobuki_comms::RobotStateEvent::OFFLINE) {
./kobuki/kobuki_factory_test/src/qnode.cpp:517:  kobuki_comms::Led led;
./kobuki/kobuki_factory_test/src/qnode.cpp:519:  for (uint8_t c = kobuki_comms::Led::GREEN; c <= kobuki_comms::Led::RED; c++) {
./kobuki/kobuki_factory_test/src/qnode.cpp:528:    led.value = kobuki_comms::Led::BLACK;
./kobuki/kobuki_factory_test/src/qnode.cpp:549:  kobuki_comms::Sound sound;
./kobuki/kobuki_factory_test/src/qnode.cpp:551:  for (uint8_t s = kobuki_comms::Sound::ON; s <= kobuki_comms::Sound::CLEANINGEND; s++) {
./kobuki/kobuki_factory_test/src/qnode.cpp:683:    kobuki_comms::DigitalOutput cmd;
./kobuki/kobuki_factory_test/src/qnode.cpp:695:      kobuki_comms::DigitalOutput cmd;
./kobuki/kobuki_factory_test/src/qnode.cpp:711:      kobuki_comms::DigitalOutput cmd;
./kobuki/kobuki_factory_test/src/qnode.cpp:721:      kobuki_comms::DigitalOutput cmd;
./kobuki/kobuki_factory_test/src/qnode.cpp:789:  led_1_pub   = nh.advertise <kobuki_comms::Led>           ("mobile_base/commands/led1", 1);
./kobuki/kobuki_factory_test/src/qnode.cpp:790:  led_2_pub   = nh.advertise <kobuki_comms::Led>           ("mobile_base/commands/led2", 1);
./kobuki/kobuki_factory_test/src/qnode.cpp:791:  sound_pub   = nh.advertise <kobuki_comms::Sound>         ("mobile_base/commands/sound", 1);
./kobuki/kobuki_factory_test/src/qnode.cpp:792:  output_pub  = nh.advertise <kobuki_comms::DigitalOutput> ("mobile_base/commands/digital_output", 1);
./kobuki/kobuki_factory_test/src/qnode.cpp:793:  ext_pwr_pub = nh.advertise <kobuki_comms::DigitalOutput> ("mobile_base/commands/external_power", 1);
./kobuki/kobuki_factory_test/src/qnode.cpp:950:          kobuki_comms::DigitalOutput cmd;
./kobuki/kobuki_factory_test/manifest.xml:11:  <depend package="kobuki_comms"/>
./kobuki/kobuki_factory_test/include/kobuki_factory_test/qnode.hpp:26:#include <kobuki_comms/SensorState.h>
./kobuki/kobuki_factory_test/include/kobuki_factory_test/qnode.hpp:27:#include <kobuki_comms/VersionInfo.h>
./kobuki/kobuki_factory_test/include/kobuki_factory_test/qnode.hpp:28:#include <kobuki_comms/DockInfraRed.h>
./kobuki/kobuki_factory_test/include/kobuki_factory_test/qnode.hpp:29:#include <kobuki_comms/ButtonEvent.h>
./kobuki/kobuki_factory_test/include/kobuki_factory_test/qnode.hpp:30:#include <kobuki_comms/BumperEvent.h>
./kobuki/kobuki_factory_test/include/kobuki_factory_test/qnode.hpp:31:#include <kobuki_comms/WheelDropEvent.h>
./kobuki/kobuki_factory_test/include/kobuki_factory_test/qnode.hpp:32:#include <kobuki_comms/CliffEvent.h>
./kobuki/kobuki_factory_test/include/kobuki_factory_test/qnode.hpp:33:#include <kobuki_comms/PowerSystemEvent.h>
./kobuki/kobuki_factory_test/include/kobuki_factory_test/qnode.hpp:34:#include <kobuki_comms/DigitalInputEvent.h>
./kobuki/kobuki_factory_test/include/kobuki_factory_test/qnode.hpp:35:#include <kobuki_comms/RobotStateEvent.h>
./kobuki/kobuki_factory_test/include/kobuki_factory_test/qnode.hpp:181:  void versionInfoCB(const kobuki_comms::VersionInfo::ConstPtr& msg);
./kobuki/kobuki_factory_test/include/kobuki_factory_test/qnode.hpp:182:  void sensorsCoreCB(const kobuki_comms::SensorState::ConstPtr& msg);
./kobuki/kobuki_factory_test/include/kobuki_factory_test/qnode.hpp:183:  void dockBeaconCB(const kobuki_comms::DockInfraRed::ConstPtr& msg);
./kobuki/kobuki_factory_test/include/kobuki_factory_test/qnode.hpp:185:  void buttonEventCB(const kobuki_comms::ButtonEvent::ConstPtr& msg);
./kobuki/kobuki_factory_test/include/kobuki_factory_test/qnode.hpp:186:  void bumperEventCB(const kobuki_comms::BumperEvent::ConstPtr& msg);
./kobuki/kobuki_factory_test/include/kobuki_factory_test/qnode.hpp:187:  void wDropEventCB(const kobuki_comms::WheelDropEvent::ConstPtr& msg);
./kobuki/kobuki_factory_test/include/kobuki_factory_test/qnode.hpp:188:  void cliffEventCB(const kobuki_comms::CliffEvent::ConstPtr& msg);
./kobuki/kobuki_factory_test/include/kobuki_factory_test/qnode.hpp:189:  void powerEventCB(const kobuki_comms::PowerSystemEvent::ConstPtr& msg);
./kobuki/kobuki_factory_test/include/kobuki_factory_test/qnode.hpp:190:  void inputEventCB(const kobuki_comms::DigitalInputEvent::ConstPtr& msg);
./kobuki/kobuki_factory_test/include/kobuki_factory_test/qnode.hpp:191:  void robotEventCB(const kobuki_comms::RobotStateEvent::ConstPtr& msg);
./kobuki/kobuki_comms/manifest.xml:10:  <url>http://www.ros.org/wiki/kobuki_comms</url>
./kobuki/kobuki_comms/.project:3:   <name>kobuki_comms</name>
./kobuki/kobuki_comms/.cproject:52:     <project id="kobuki_comms.null.1503953267" name="kobuki_comms"/>
./kobuki/kobuki_arm/scripts/arm_controller.py:5:from kobuki_comms.msg import SensorData
./kobuki/kobuki_keyop/src/keyop_core.cpp:222:void KeyOpCore::remoteKeyInputReceived(const kobuki_comms::KeyboardInput& key) {
./kobuki/kobuki_keyop/src/keyop_core.cpp:242:       case kobuki_comms::KeyboardInput::KeyCode_Left: {
./kobuki/kobuki_keyop/src/keyop_core.cpp:246:       case kobuki_comms::KeyboardInput::KeyCode_Right: {
./kobuki/kobuki_keyop/src/keyop_core.cpp:250:       case kobuki_comms::KeyboardInput::KeyCode_Up: {
./kobuki/kobuki_keyop/src/keyop_core.cpp:254:       case kobuki_comms::KeyboardInput::KeyCode_Down: {
./kobuki/kobuki_keyop/src/keyop_core.cpp:258:       case kobuki_comms::KeyboardInput::KeyCode_Space: {
./kobuki/kobuki_keyop/manifest.xml:18:  <depend package="kobuki_comms"/>
./kobuki/kobuki_keyop/include/keyop_core/keyop_core.hpp:25:#include <kobuki_comms/KeyboardInput.h> // keycodes from remote teleops.
./kobuki/kobuki_keyop/include/keyop_core/keyop_core.hpp:87: void remoteKeyInputReceived(const kobuki_comms::KeyboardInput& key);
./kobuki/kobuki_testsuite/scripts/test_translation.py:41:from kobuki_comms.msg import BumperEvent
./kobuki/kobuki_testsuite/scripts/test_translation.py:42:from kobuki_comms.msg import Sound
./kobuki/kobuki_testsuite/scripts/test_analog_input.py:42:from kobuki_comms.msg import SensorState
./kobuki/kobuki_testsuite/scripts/test_battery_voltage.py:42:from kobuki_comms.msg import SensorState
./kobuki/kobuki_testsuite/scripts/test_led_array.py:38:from kobuki_comms.msg import Led
./kobuki/kobuki_testsuite/scripts/test_digital_output.py:38:from kobuki_comms.msg import DigitalOutput
./kobuki/kobuki_testsuite/scripts/test_input.py:46:from kobuki_comms.msg import SensorState
./kobuki/kobuki_testsuite/scripts/test_input.py:47:from kobuki_comms.msg import ButtonEvent
./kobuki/kobuki_testsuite/scripts/test_input.py:48:from kobuki_comms.msg import BumperEvent
./kobuki/kobuki_testsuite/scripts/test_input.py:49:from kobuki_comms.msg import WheelDropEvent
./kobuki/kobuki_testsuite/scripts/test_input.py:50:from kobuki_comms.msg import CliffEvent
./kobuki/kobuki_testsuite/scripts/test_input.py:51:from kobuki_comms.msg import PowerSystemEvent
./kobuki/kobuki_testsuite/scripts/test_input.py:52:from kobuki_comms.msg import DigitalInputEvent
./kobuki/kobuki_testsuite/scripts/test_events.py:38:from kobuki_comms.msg import ButtonEvent
./kobuki/kobuki_testsuite/scripts/test_events.py:39:from kobuki_comms.msg import BumperEvent
./kobuki/kobuki_testsuite/scripts/test_events.py:40:from kobuki_comms.msg import WheelDropEvent
./kobuki/kobuki_testsuite/scripts/test_events.py:41:from kobuki_comms.msg import CliffEvent
./kobuki/kobuki_testsuite/scripts/test_events.py:42:from kobuki_comms.msg import PowerSystemEvent
./kobuki/kobuki_testsuite/scripts/test_events.py:43:from kobuki_comms.msg import DigitalInputEvent
./kobuki/kobuki_testsuite/scripts/test_output.py:43:from kobuki_comms.msg import DigitalOutput, Led, Sound
./kobuki/kobuki_testsuite/scripts/test_external_power.py:43:from kobuki_comms.msg import DigitalOutput
./kobuki/kobuki_testsuite/scripts/test_sounds.py:38:from kobuki_comms.msg import Sound
./kobuki/kobuki_testsuite/src/kobuki_testsuite/motion_wander.py:20:from kobuki_comms.msg import BumperEvent, CliffEvent
./kobuki_desktop/kobuki_qtestsuite/src/kobuki_qtestsuite/battery_profile_frame.py:25:from kobuki_comms.msg import RobotStateEvent
jihoonl@whoolala:~/ttt$

**Comment by jihoonl** [comment]
Wait until Jorge finishes factory test program.

**Comment by stonier** [comment]
I would actually do before he finishes it. The work on his end is minimal. We can quickly hack the changes in the morning.

**Comment by jihoonl** [comment]
Done 59121fe096e1ee298b79675f73ff84cfeb828192
