### ISSUE TITLE
kobuki_fuerte.rosinstall need to be fixed.

### ISSUE THREAD

**Issue by jihoonl** [yujinrobot/kobuki#163]
[ecl/ecl_tools] Installing https://embedded-control-library.googlecode.com/svn/tags/ecl_tools (version fuerte) to /home/jihoonl/kobuki_sbc/ecl/ecl_tools
svn: Syntax error in revision argument 'fuerte'
[ecl/ecl_lite] Installing https://embedded-control-library.googlecode.com/svn/tags/ecl_lite (version fuerte) to /home/jihoonl/kobuki_sbc/ecl/ecl_lite
svn: Syntax error in revision argument 'fuerte'
[ecl/ecl_core] Installing https://embedded-control-library.googlecode.com/svn/tags/ecl_core (version fuerte) to /home/jihoonl/kobuki_sbc/ecl/ecl_core
svn: Syntax error in revision argument 'fuerte'
[ecl/ecl_navigation] Installing https://embedded-control-library.googlecode.com/svn/tags/ecl_navigation (version fuerte) to /home/jihoonl/kobuki_sbc/ecl/ecl_navigation
svn: Syntax error in revision argument 'fuerte'

Exception caught during install: Error processing 'ecl/ecl_tools' : [ecl/ecl_tools] Checkout of https://embedded-control-library.googlecode.com/svn/tags/ecl_tools version fuerte into /home/jihoonl/kobuki_sbc/ecl/ecl_tools failed.
Error processing 'ecl/ecl_lite' : [ecl/ecl_lite] Checkout of https://embedded-control-library.googlecode.com/svn/tags/ecl_lite version fuerte into /home/jihoonl/kobuki_sbc/ecl/ecl_lite failed.
Error processing 'ecl/ecl_core' : [ecl/ecl_core] Checkout of https://embedded-control-library.googlecode.com/svn/tags/ecl_core version fuerte into /home/jihoonl/kobuki_sbc/ecl/ecl_core failed.
Error processing 'ecl/ecl_navigation' : [ecl/ecl_navigation] Checkout of https://embedded-control-library.googlecode.com/svn/tags/ecl_navigation version fuerte into /home/jihoonl/kobuki_sbc/ecl/ecl_navigation failed.

ERROR in config: Error processing 'ecl/ecl_tools' : [ecl/ecl_tools] Checkout of https://embedded-control-library.googlecode.com/svn/tags/ecl_tools version fuerte into /home/jihoonl/kobuki_sbc/ecl/ecl_tools failed.
Error processing 'ecl/ecl_lite' : [ecl/ecl_lite] Checkout of https://embedded-control-library.googlecode.com/svn/tags/ecl_lite version fuerte into /home/jihoonl/kobuki_sbc/ecl/ecl_lite failed.
Error processing 'ecl/ecl_core' : [ecl/ecl_core] Checkout of https://embedded-control-library.googlecode.com/svn/tags/ecl_core version fuerte into /home/jihoonl/kobuki_sbc/ecl/ecl_core failed.
Error processing 'ecl/ecl_navigation' : [ecl/ecl_navigation] Checkout of https://embedded-control-library.googlecode.com/svn/tags/ecl_navigation version fuerte into /home/jihoonl/kobuki_sbc/ecl/ecl_navigation failed.

**Comment by stonier** [comment]
They have working debs, so removed ecl/zeroconf_implementations. I'll check it again later.
