### ISSUE TITLE
Publish raw data stream from robot for debugging

### ISSUE THREAD

**Issue by yhju** [yujinrobot/kobuki#170]

**Comment by yhju** [comment]
Implemented in 116aa7116c7e9d4aae3261eb5bbbfea6c3e4fbb5 and 1e27089ab10067f6b452c75c7c42caef2d0cb2a8.
But little bit unstable.

**Comment by stonier** [comment]
What do you mean by unstable? Does it crash kobuki?

**Comment by yhju** [comment]
Look #172

**Comment by yhju** [comment]
I am waiting for Daniel's fix of ecl.

**Comment by stonier** [comment]
The formatter fix is in:

 https://github.com/stonier/ecl_core/issues/1

but won't be in debs for a while yet. I'll update it when it is.
