### ISSUE TITLE
Kinect power connector upside down

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#171]
The Kobuki power connector for the Kinect has Power and ground swapped.

On turtlebot 1, ground is farthest from the clip.
On kobuki, the ground pin is closest to the clip.

From tully:

@stonier Can you double check this? This sounds like a pretty big problem.

**Comment by stonier** [comment]
I had hoped to get an email to the turtlebot sig out about this earlier this week instead of having it get noisy here, but have been awol with food poisoning for a couple of days.

I'll get an email out immediately.

**Comment by mikeferguson** [comment]
Pin 1 should always be ground (this has been a Willow Garage standard for a long time an is the case on both PR2 and the original TurtleBot). In the case of a 2P Molex Mini-Fit Jr, pin 1 is the pin away from the latch/clip.

**Comment by mmwise** [comment]
I think that it's important to fix this so that we have backwards compatibility. We are most likely going to have many users upgrading and not reading the docs before pulling things in.

**Comment by stonier** [comment]
Please see the sig email.

**Comment by mmwise** [comment]
Have you sent a sig email? i just looked at the ros-sig-tbot list archives there is no email

**Comment by stonier** [comment]
Did you go to the old one mel? I sent to the new one Tully made at google groups:
- https://groups.google.com/forum/#!topic/ros-sig-turtlebot/cBt7q6wvSb4

**Comment by mmwise** [comment]
Yeah, I had no idea that list existed. that's why I haven't been responding cause I wasn't getting emails.

**Comment by stonier** [comment]
Spank Tully ;)

**Comment by stonier** [comment]
Continue to resolve things via the sig.
