### ISSUE TITLE
Too many timed out error on kobuki_node

### ISSUE THREAD

**Issue by yhju** [yujinrobot/kobuki#174]
```
[ WARN] [1353578648.966081309]: Incoming velocity commands not received for more than 0.60 seconds -> zero'ing velocity commands
[ WARN] [1353578662.465921160]: Incoming velocity commands not received for more than 0.60 seconds -> zero'ing velocity commands
[ERROR] [1353578674.017219161]: Kobuki : timed out waiting for the serial data stream [/mobile_base].
[ WARN] [1353578675.999407733]: Incoming velocity commands not received for more than 0.60 seconds -> zero'ing velocity commands
[ERROR] [1353578682.000222124]: Kobuki : timed out waiting for the serial data stream [/mobile_base].
[ERROR] [1353578684.554202732]: Kobuki : timed out waiting for the serial data stream [/mobile_base].
```

**Comment by stonier** [comment]
Still seeing this....not good before having to show the robots.

**Comment by stonier** [comment]
Is this and #173 starting only after the flexible protocol update?

**Comment by yhju** [comment]
In my case, it occurred on virtual machine only, not on native machine. 
Or when I start `minimal.launch` without turning the power on the robot first.

**Comment by stonier** [comment]
- Can you find out exactly why the virtual machine makes the error...that may help us understand.
- Is it always reproducible on the virtual machine?

**Comment by stonier** [comment]
We managed to reproduce just once on a laptop and robot that were both low on battery.

Keep an eye out for this, and if it happens, let's grab the hardware guys immediately.

**Comment by stonier** [comment]
http://answers.ros.org/question/52203/kobuki-malformed-subpayload/

He had usb dropouts too.

**Comment by stonier** [comment]
I think this has been fixed by some firmware updates and packet validation issue above. 

Reopen if necessary.
