### ISSUE TITLE
Gracefully abort if correct firmware is not matching

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#175]
Check against the firmware version and gracefully abort.
- Provide a decent error message to the user.
- Provide a url to http://kobuki.yujinrobot.com/documentation/howtos/upgrading-firmware/

**Comment by stonier** [comment]
Might also be worth matching our uploaded firmware .hexname  to the version string received by the driver. Ask marcus, young hoon about that.

Btw, what is the difference between hardware and software version in kobukis version info?

**Comment by corot** [comment]
After talking with RnD guys, we think a good idea is to signal incompatibility between firmware and driver by changing the second figure in the firmware version.

The three figures of Firmware number will mean:
- major release
- minor release that will force upgrade firmware, OR a patch that changes protocol (and so comptatibility)
- patch that doesn't break compatibility

So the check in the driver will be against something like 1.0.?. This can be done within the 2 bytes we have now for the version number by converting them into a string, so no need to change the firmware.

**Comment by stonier** [comment]
Will catch up with you wed morning about this.

**Comment by corot** [comment]
Factory version will be 1.0.0, but at it's actually hardcoded as 1.2.3, we will add a dirty temporal hack in the driver to change it to 1.0.0.

MENTAL NOTE: please, please, please remove this horrible hack wit the first firmware change (1.0.1)

**Comment by corot** [comment]
Done, but when launching as nodelet doesn't show the proper message, as we only use standard rosconsole macros.
I add a comment on issue #166

**Comment by stonier** [comment]
Factory version is actually 0.0.2. I updated the file server for this information: http://files.yujinrobot.com/kobuki/firmware/

So if the software is configured for 0.1.x and is running ok, but the next software update is now looking for 0.2.x and it only finds 0.1.x it will complain?

Also, just out of curiosity, where is the kobuki driver software version set?
