### ISSUE TITLE
Always failed to build kobuki_qtestsuite

### ISSUE THREAD

**Issue by yhju** [yujinrobot/kobuki#181]
Is there any guide or tutorial on [this](http://blog.yujinrobot.com/2012/11/kobuki-test-suite-with-rqt.html)?

**Comment by stonier** [comment]
Fuerte or groovy?

rqt updating alot these days, I might have to occasionally fix it.

**Comment by yhju** [comment]
Both of distro's. OK, I'll be waiting.

**Comment by stonier** [comment]
It's segfaulting on groovy...issue is being picked up at https://github.com/ros-visualization/rqt/issues/16

Workaround for our programs is to delete the cpp bindings (we're only using pyqt plugins, so is ok for now).

```
sudo rm /opt/ros/groovy/lib/python2.7/dist-packages/qt_gui_cpp/libqt_gui_cpp_sip.so
```
