### ISSUE TITLE
Button not working when power up the robot with long-pressing touch button.

### ISSUE THREAD

**Issue by yhju** [yujinrobot/kobuki#182]
Both on 0.0.2 and 0.1.0

**Comment by jakan2** [comment]
- Yes, this is known issue 
- We need to hardware engineer

**Comment by jakan2** [comment]
HyoungJu fixed this issue with supplier. 
He will check when it is available.

**Comment by jakan2** [comment]
It is already available
we have to send the ecn

**Comment by stonier** [comment]
Ah, i get it....pressing button and turning on at the same time (usually when moving).

**Comment by jakan2** [comment]
HJ will publish the ecn to factory. 
I will ask on Friday

**Comment by jakan2** [comment]
Process done. 
Next product will have valid touch button
