### ISSUE TITLE
Make sure all messages are published as shared pointers

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/kobuki#183]
In order to leverage the zero-copy pub/sub feature of nodelets, we need to make sure that we are publishing shared pointers.

So,  **NOT** like this:

``` c++
std_msgs::String msg;
msg.data = "TestString";
publisher.publish(msg);
```

but like this:

``` c++
std_msgs::StringPtr msg(new std_msgs::String);
msg->data = "TestString";
publisher.publish(msg);
```

**Comment by corot** [comment]
mmm....  I had no idea

**Comment by stonier** [comment]
Did they put any information about the non-const shared pointer passing in nodelets on the ros wiki?

**Comment by corot** [comment]
TODO:
- <del>kobuki_node</del>
- <del>vel_smoother</del>
- <del>cmd_vel_mux</del>
- <del>safety_controller</del>
- <del>turtlebot_follower</del>
- <del>bump_blink_controller</del>
- auto_docking

Which one more? We have no more nodelets on kobuki workspace, but one of this days we should take a look also to YCS, CSlam, etc.

**Comment by corot** [comment]
For turtlebot_follower don't make so much sense, because as it's intended to work inside the camera node, it doesn't publish to his neighbors

**Comment by stonier** [comment]
It is a good habit though. Shared pointers don't cost anything, but non shared objects sometimes create the bug.

**Comment by stonier** [comment]
Closing this...keep it in mind when coding lads!
