### ISSUE TITLE
Nodelets not shutting down

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#185]
It hangs - sigterm'ing on a ctrl-c.

Not sure if this is when run standalone or if it only happens once other nodelets are loaded in as well. 
Check.

Also the safety controller is sometimes hanging (maybe because of kobuki?)

**Comment by stonier** [comment]
Once on exit (with no other nodelets loaded):

```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost::lock_error
```

**Comment by bit-pirate** [comment]
Couldn't reproduce this on my system with stable nor shadow-fixed.

2012/12/2 Daniel Stonier notifications@github.com

> Once on exit (with no other nodelets loaded):
> 
> terminate called after throwing an instance of 'boost::exception_detail::clone_implboost::exception_detail::error_info_injector<boost::lock_error >'
>   what():  boost::lock_error
> 
>  --
> Reply to this email directly or view it on GitHubhttps://github.com/yujinrobot/kobuki/issues/185#issuecomment-10924235.

## 

Marcus Liebhardt
Adresse: Zimmer 403, 634-1 Seongsan-dong, Mapo-gu, Seoul, Republik Korea
Address: Room 403, 634-1 Seongsan-dong, Mapo-gu, Seoul, Republic of Korea
주소: 대한민국 서울특별시 마포구 634-1 성산동 4 층 403 호
Mobile / Mobilfunk: +82 10 3322 0566
Email: ich@marcusliebhardt.de ich@marcusliebhardt.de

**Comment by bit-pirate** [comment]
Ha, I found a way to reproduce it:

Start kobuki_node/minimal.launch in one terminal, then kobuki_node/keyop.launch in a second.

Now, when you **first kill** the launcher containing the **nodelet_manager** (minimal.launch) and afterwards the other nodes and nodelets (keyop.launch), everything shuts down nicely.

However, when I first kill the launch with extra nodes and nodelets and afterwards the nodelet manager's launch, then it only finishes after SIGTERM.

Could someone else try this, please? Sounds like a nodelet (manager) problem/bug.

**Comment by corot** [comment]
Same behavior. I think it's related with the worker thread we use, cause cmd_vel_mux (who has no thread) shutdowns gently. I'm taking a look now.

**Comment by corot** [comment]
Ok; I crack the nut; We rely on ros::ok() to terminate the threads, but ros::ok() remains true if we only kills the nodelets, but not the nodelet_manager. So we just need an extra flag to signal our threads to shutdown gently.

**Comment by corot** [comment]
Done for vel smoother and safety ctrl. Somewhere else?
