### ISSUE TITLE
Kobuki controllers into kobuki

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#186]
We have no reason to make this a separate stack. Or do we?

The dependencies are the same as for kobuki. And I want to avoid having to maintain another deb release.

**Comment by bit-pirate** [comment]
Just wanted to split things according to their domain and avoid the kobuki stack get too crowded. I don't have any objections about moving controllers thought ...

**Comment by stonier** [comment]
Lets keep it simple and merge. Only create extra work for us (i.e. releasing) if we need to. I usually have two reasons for creating a new stack:
- some parts of the stack require esoteric dependencies that users sometimes can't depend on. e.g. a stack , some without qt deps and some with qt deps for an embedded rosinstall.
- when there is no relation between packages and users will _very_ often install one but not the other (e.g. ycs_manipulation vs ycs_navigation.

**Comment by bit-pirate** [comment]
_thumb up_

2012/12/2 Daniel Stonier notifications@github.com

> Lets keep it simple and merge. Only create extra work for us (i.e.
> releasing) if we need to. I usually have two reasons for creating a new
> stack:
> - some parts of the stack require esoteric dependencies that users
>   sometimes can't depend on. e.g. a stack , some without qt deps and some
>   with qt deps for an embedded rosinstall.
> - when there is no relation between packages and users will _very_often install one but not the other (e.g. ycs_manipulation vs
>   ycs_navigation.
>   
>   ## 
>   
>   Reply to this email directly or view it on GitHubhttps://github.com/yujinrobot/kobuki/issues/186#issuecomment-10925808.

## 

Marcus Liebhardt
Adresse: Zimmer 403, 634-1 Seongsan-dong, Mapo-gu, Seoul, Republik Korea
Address: Room 403, 634-1 Seongsan-dong, Mapo-gu, Seoul, Republic of Korea
주소: 대한민국 서울특별시 마포구 634-1 성산동 4 층 403 호
Mobile / Mobilfunk: +82 10 3322 0566
Email: ich@marcusliebhardt.de ich@marcusliebhardt.de
