### ISSUE TITLE
Yujin control library - namespace and structure

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#187]
open_control_library -> yujin_control

Jihoon made a good point - this associates yujin with the stack (shows up on the meta-deb and the ros wiki) and follows ros convention (e.g. bosch_xxx).

We're not doing groundbreaking control library stuff with the community, so this makes sense.

The internal mixup with ycs is really a minimal issue. Outside is more important.

Sort this out so we can deb release!

Thoughts?

**Comment by bit-pirate** [comment]
The stack has already been renamed to yujin_ocl.
So, close?
