### ISSUE TITLE
add/update ROS package descriptions

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/kobuki#188]
So, that the ROS wiki actually contains some info about our packages.

Please take care about up-to-date info and good spelling. This is very visible on the ROS wiki (#1 place of information for most Kobuki/Turtlebot users!).

Have a look at these pacakges:
- kobuki_arm
- kobuki_keyop
- kobuki_node
- kobuki_testsuite
- kobuki_ftdi

**Comment by bit-pirate** [comment]
The last commits should include the packages listed above and more. Will wait for the indexer to parse the new information before closing this.

**Comment by stonier** [comment]
Should be all done (cept for kobuki_arm). Reopen if necessary.
