### ISSUE TITLE
rename kobuki_node's default velocity command input topic

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/kobuki#191]
... from currently "node_name/cmd_vel" to "node_name/commands/velocity".
This aligns with the other inputs/commads, e.g. "node_name/commands/led1".

**Comment by stonier** [comment]
it is already done.

**Comment by bit-pirate** [comment]
done (forgot to ref it)

**Comment by bit-pirate** [comment]
yeah, i saw. had to recompile it -.-

**Comment by stonier** [comment]
I did it with various other things last night.
