### ISSUE TITLE
add example/standalone launchers and config files

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/kobuki#192]
... for each package containing executables (also nodelets).
Otherwise the user (includes us) has to go hunting for topic and parameter names in source code.

TODO:
- [x] kobuki_arm (currently not used -> not necessary)
- [x] kobuki_auto_docking
- [x] kobuki_controller_tutorial
- [x] kobuki_ftdi
- [x] kobuki_keyop
- [x] kobuki_node
- [x] kobuki_safety_controller
- [x] kobuki_testsuite

**Comment by bit-pirate** [comment]
Jorge, I already added files to the smoother. Please have a look at the parameters, if they make sense (e.g. in the use case of kobuki). Then please also update the keyop_smoother config file in kobuki_node. thx!

**Comment by corot** [comment]
Done for smoother and multiplexer.
keyop_smoother is ok. Just we should play a bit to decide good accel. limits for every robot and reuse again and again, and redefine only in the launch file in cases where we need something more specific. I always fear exploding the configuration complexity...

**Comment by stonier** [comment]
Kobuki ftdi isn't necessary, it's just direct non-ros executables.

**Comment by stonier** [comment]
Kobuki utilities is gone.

**Comment by bit-pirate** [comment]
- For kobuki_node minimal.launch + params should be enough.
- Standalone launcher for kobuki_controller_tutorial added.

**Comment by bit-pirate** [comment]
@stonier is the kobuki_testsuite supposed to be launched alone or incombination with the kobuki_node?
The launcher in there looks a bit outdated (e.g. contains turtlebot comments).

**Comment by stonier** [comment]
Probably delete those launchers - they're not official and not documented anywhere. Currently their main purpose is for use by kobuki_qtestsuite.

**Comment by bit-pirate** [comment]
@yhju is using this launcher. So I just removed the turtlebot stuff in the comments.
I also added a readme to point out that this package is mainly used by kobuki_qtestsuite. Hence, I added no standalone launcher.

**Comment by bit-pirate** [comment]
All done now.
