### ISSUE TITLE
Safeties for firmware random wanderer

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/kobuki#193]
Shall we add cliff/wheel drop safeties to our firmware wanderer?

**Comment by corot** [comment]
I think our Eisenstein has been quite idle recently...  yesterday he left the office before midnight, so I vote YES for the extra safety (we are in a safety-passionate country, isn't it?)

**Comment by bit-pirate** [comment]
This is related to: https://github.com/yujinrobot/kobuki/issues/212

**Comment by stonier** [comment]
If this is more than 10mins of work Einstein, drop it, otherwise do it with the PID changes.

**Comment by jakan2** [comment]
A new firmware already includes this function. 
Close
