### ISSUE TITLE
Check behaviour of enable/disabling the safety controller on runtime

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/kobuki#198]
I think this is not working correctly.

**Comment by stonier** [comment]
We need to review this next week - I couldn't get it working sensibly for turtlebot.

**Comment by corot** [comment]
What's the problem?  I did it on waiterbot and saw no problems

**Comment by stonier** [comment]
Marcus wll check this is actually going on.

**Comment by bit-pirate** [comment]
Just tested it again and looks good. Also, Jorge was using it extensively during the ROCON cafe demo.
