### ISSUE TITLE
Kobuki Description

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#20]
Match our kobuki_description with the turtlebot_description package. Maybe even utilise some of it.

**Comment by stonier** [comment]
Added a rear wheel to the xacro.

**Comment by bit-pirate** [comment]
applied turtlebot_description structure; urdf visualisation in rviz works; proper gazebo simulation still TODO

**Comment by bit-pirate** [comment]
applied turtlebot_description structure; urdf visualisation in rviz works; proper gazebo simulation still TODO

**Comment by bit-pirate** [comment]
The necessary files for the Gazebo simulation are mostly only a modified copy of the turtlebot/create. We need to update and adapt them to the actual Kobuki, e.g. simulate the sensor we have. Also, we still need to get a nice mesh for our robot. Hence, I'll keep this issue open.

**Comment by corot** [comment]
Not sure if this should be a new issue by its own.... 

We are till now ignoring kinect calibration parameters (stored on file turtlebot_calibration.xacro). We have by now a default calibration that I have no idea from where it comes from. Probably from Turtlebot default values. I think we should provide an all-zeros file and a procedure for calibration similar to the turtlebot one (no idea how it looks).

By now, 민수 will manually estimate approximate values for his 케봇

**Comment by bit-pirate** [comment]
DK and I are now working on an precise kinematic model and a nice mesh.

**Comment by bit-pirate** [comment]
@ calibration file: It is use to properly place the Kinect on top of Kobuki (resp. the iCreate). After the design is fixed, we need to write down the correct values for the Kinect and Xtion.

**Comment by bit-pirate** [comment]
I just pushed my updates, restructing and cleaning work. RViz visualisation works, but loading the same robot description looks stange in Gazebo (although the simulation itself works).  Others are experiencing the same issue: [here](https://kforge.ros.org/gazebo/trac/ticket/59) and [here](http://answers.ros.org/question/32849/visual-and-collision-geometry-misaligned-in-gazebo-10/). Hopefully, that gets solved by a new Gazebo release.  I'll keep an eye on this.

Further updates are still on the list: Add new high- and low-res hexagon plate and base meshes, make use of Collada and test the 3d sensor simulation.

**Comment by bit-pirate** [comment]
Done. Kobuki and Turtlebot 2 look awesome! :-)
