### ISSUE TITLE
Software version info - unimplemented

### ISSUE THREAD

**Issue by corot** [yujinrobot/kobuki#201]
Driver version: to decide how to do; by now we put a banner "STILL NOT IMPLEMENTED"

**Comment by stonier** [comment]
Have to wait for #205 (Catkinize) - I can't pass the stack version number through to the package build.

**Comment by corot** [comment]
Now I can do this....   but unfortunately I don't know how

**Comment by yhju** [comment]
I have a solution, I am working on it now.

**Comment by yhju** [comment]
Implemented by d48175ab2413a729ddb2391a733abf78784e9a6e, c9c0b453dace93e135358742a46a6ae843eab5af and 8ed797b4b98292057970f168f176c27d72bf1709. 
Done.
