### ISSUE TITLE
what are kobuki_usb_tools

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#204]
Young Hoon,

This is a very good example of reinventing the wheel and making things confusing.
- We now have two ftdi packages doing the same thing - why did you create a new one?
- Broken documentation for kobuki_ftdi now because functionality is elsewhere.
- No documentation for kobuki_usb_tools - no idea what does what.
- No information on what or how it is used at the factory.

In other words, if you leave, we waste alot of time trying to work out what was in your head.

Fix this, and please communicate when you build something.

**Comment by stonier** [comment]
These programs are all now in kobuki_ftdi. 

They still need documentation and a cleanup.

**Comment by yhju** [comment]
The kobuki_usb_tools package is used in flashing serial number of new ftdi chip on kobuki, in manufacturing process with Jorge's final test program. Each binaries in the package has obvious roles, even though some programs reuses some portion of the source code from the kobuki_ftdi package. And it was the job you gave to me.

The final test program will call these binaries on runtime, to handle some sort of usb related jobs. Like below:
- **find_devices** - detect the presence of kobuki robot(exactly, the ftdi chip), either flashed with 'kobuki_' prefix or not.
- **get_serial_number** - read serial number of ftdi chip.
- **flasher** - flash ftdi chip's serial number with 'kobuki_' prefix.
- **reset_device** - reset specific usb connection after flashing serial number, to load ftdi device as standard tty device without actual re-plugging of usb connector. If successful, a device file `/dev/kobuki` will appear.
- **overwrite_serial_number** - overwrites serial number of ftdi chip to test above functionality repeatedly with just one robot. (test only)

Jorge's final test program was once located in kobuki_final_test package of kobuki_desktop stack. So, I made kobuki_usb_tools package on that stack. But now final test program is located in our internal repository. 

In my opinion, above specialized functionality is not very useful for general users, except **reset_device**.  So, I want to suggest to move kobuki_usb_tools to our internal repository with **good documentation**, and add **reset_device** on kobuki_ftdi package.

**Comment by stonier** [comment]
As we discussed, it's worth having the code in the wild - I think alot of people are interested in being able to flash their usb devices.

So two approaches:

1) develop, release and support a general usb tools package or
2) just a kobuki_ftdi specific package

1) is more work than you would think, and we don't have testing resources to do it properly anyway. 2) is nice, it opens the code, but we provide no guarantees and don't have the maintenance overhead.
