### ISSUE TITLE
rosdep broken

### ISSUE THREAD

**Issue by yhju** [yujinrobot/kobuki#210]
In groovy on precise

```
$ rosdep check -a
System dependencies have not been satisified:
apt texlive-latex-base
apt texlive-latex-recommended
apt texlive-latex-extra
apt texlive-fonts-recommended
apt libftdi-dev
apt texlive-fonts-extra
apt ftdi-eeprom
ERROR[kobuki_auto_docking]: resource not found [actionlib]
ERROR[ecl_doc]: resource not found [rosdoc]
ERROR[kobuki_qtestsuite]: resource not found [qt_gui_py_common]
ERROR[kobuki_gazebo_plugins]: resource not found [create_node]
ERROR[kobuki_gazebo]: resource not found [robot_pose_ekf]
```

**Comment by stonier** [comment]
The `resource not found` messages are looking for ros packages. Most of the above just mean you've not got the appropriate debs installed. Of the others - 
- `ecl_doc`. I suspect your ecl is old. Delete the sources and download the ecl debs. 
- `kobuki_gazebo_plugins` - looks like your install doesn't have turtlebot_create stack.
