### ISSUE TITLE
version info tool for kobuki_driver

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/kobuki#213]
Currently there is no easy way for non-ROS users to find out, which firmware version their Kobuki is running.

Let's add a minimalistic program, which when called prints version info to the screen.

**Comment by yhju** [comment]
Done by ce853984f5047047465f7259c0989a3c48922378 and c0ed549054eee47518ecff50c9cbcc1f2514708a.

**Comment by yhju** [comment]
This program's name is `version_info`, and it's source code(`version_info.cpp`) is located under the `kobuki_driver/src/test` for now. 

Is it suitable place for it?

**Comment by bit-pirate** [comment]
I would put it in a folder named like "tools" or where ever you put your other programs in. "test" could be misleading, since its not a unit test or similar.

**Comment by stonier** [comment]
ditto to marcus comment.

I usually use 'src/utils' for this kind of thing.

**Comment by yhju** [comment]
OK. I moved it to `src/tools` directory.
Thanks
