### ISSUE TITLE
Parameterize waiting option for the absence of the device.

### ISSUE THREAD

**Issue by yhju** [yujinrobot/kobuki#215]
It blocks kobuki.init() call without notice, when using it as c++ driver.

https://github.com/yujinrobot/kobuki/blob/groovy-devel/kobuki_driver/src/driver/kobuki.cpp#L101

**Comment by stonier** [comment]
Currently hardcoded at 5seconds.

**Comment by stonier** [comment]
Parameterising it actually won't help the user as it just loops.

He needs to make the info slot to get recognition.

No user needs this immediately, so dropping for now.
