### ISSUE TITLE
uint16_t undeclared in scanner.hpp on gcc 4.7

### ISSUE THREAD

**Issue by pallegro** [yujinrobot/kobuki#220]
kobuki/kobuki_ftdi/include/kobuki_ftdi/scanner.hpp:63:49: error: ‘uint16_t’ has not been declared

fix:
 #include <usb.h>
+#include <stdint.h>

**Comment by yhju** [comment]
Did you installed `libusb-dev`? 
I think it is dependency problem. 
`usb.h` from `libusb-dev` includes `stdint.h`, which is has declaration of `uint16_t`.

**Comment by stonier** [comment]
It doesn't matter about the dependency.

We actually use uint16_t, so a _good habit_ is to always include the header (here <cstdint> or <stdint.h>) and not trust the dependency. Never trust the dependency!

This is a good example of not doing that good habit. Our libusb-dev may have that magic include, so its ok. Another linux system may have a different version or implementation which doesn't. So our code breaks. Better to have the include so our code can never break.

Can you (Young Hoon) or Jorge put it in?

**Comment by yhju** [comment]
Updated. Thank you for your comment.

**Comment by stonier** [comment]
0027b57fea017e610baa226b6645a5a1c071f05c (stdint) and 087aa595f7c93ed7f34c3fb9db5629532bdf972a (libusb-dev)

**Comment by stonier** [comment]
Closing. @pallegro, reopen if you still have problems.
