### ISSUE TITLE
Motor enabled/disabled indication

### ISSUE THREAD

**Issue by jihoonl** [yujinrobot/kobuki#223]
Motor enable/disable is indicated only on screen output of kobuki driver and kobuki dashbaord. It may be nice if Kobuki itself can tell the motors are disabled.(i.e. Status LED blinking, color shifting, or etc)

**Comment by bit-pirate** [comment]
Indicating a lot with just the one LED we have for Kobuki (since the other 2 are for the user), might become confusing.

Maybe we can come up with ideas about using the other two LEDs without disturbing possible users.

Or what about adding a sound for this?

**Comment by jihoonl** [comment]
Adding sound would be another option. But what if an user disabled the motors and another user starts to use. It is hard to know whether it is previously disabled or not without dashboard or screen log.

**Comment by stonier** [comment]
Dropping this one as a won't do. Low value with potential nuisance effects unless a suitable idea presents itself. If that happens, we can open an issue and work on it then.
