### ISSUE TITLE
apt-get kobuki does not set udev rule.

### ISSUE THREAD

**Issue by jihoonl** [yujinrobot/kobuki#224]
I had to manually make udev in kobuki_ftdi after apt-get kobuki

Hope this happen automatically

**Comment by stonier** [comment]
The installation instructions on the [wiki](http://ros.org/wiki/turtlebot/Tutorials/groovy/Installation) cover this extra step.

I also wanted to make it happen automatically, so I [asked the buildsystem sig](https://groups.google.com/forum/#!topic/ros-sig-buildsystem/Dw2iKzkWO9Q) about installing stuff directly into /etc/udev last week, and while you _kinda_ can, there are a few ways this breaks with the current catkin built debs.
- Installing ros-groovy-kobuki and subsequently /etc/udev/rules.d/57-kobuki.rules will fail with a conflict when you try and install ros-hydro-kobuki
- Installing 57-kobuki-groovy.rules and 57-kobuki-hydro.rules will result in undefined behaviour. You could have hydro rules firing when running a groovy environment. Is ok if the rules dont change from groovy to hydro...but fragile and not a proper solution.
- Creating a proper rosdep for it that matches the ubuntu version, not the ros version might be the proper way to go. But then you need to add a launchpad ppa (or use Bill's) to do this.

I think the last option is probably the best for now - use the ros repo for ros debs and bill's ppa for ubuntu system debs.

Ideas?

**Comment by stonier** [comment]
Doesn't look like ros packaging will support very conveniently a way to install to the system for some time yet. So...we need to make our own debs for things like this udev rule and get_serial_info. Lean on Bill's launchpad (short term) or just start our own (better long term).

**Comment by stonier** [comment]
Done in https://github.com/yujinrobot/kobuki_core/pull/28
