### ISSUE TITLE
Kobuki_node crashes when no robot is connected

### ISSUE THREAD

**Issue by corot** [yujinrobot/kobuki#225]
For example, this happens if we unplug kobuki:

[ERROR] [1361169093.162705418]: Kobuki : Device does not exist.
[ERROR] [1361169093.246807871]: Kobuki : Timed out while waiting for serial data stream [/mobile_base].
terminate called after throwing an instance of 'ecl::StandardException'
  what():  
Location : /opt/kobuki_catkin/src/ecl_core/ecl_devices/src/lib/serial_pos.cpp:91 
Flag     : Unknown error.
Detail   : Unknown errno 113 [No route to host]

**Comment by yhju** [comment]
I am now testing turtlebot 2.0 debs in ros-shadow-fixed by following roswiki tutorials. And I've found `/dev/kobuki` is linked to `/dev/rfcomm0`, which is bluetooth device, when usb is not connected. 

So, I suggest to do test again, after disabling bluetooth rules in `/etc/udev/rules.d/57-kobuki.rules`

here is example:

```
# On precise, for some reason, USER and GROUP are getting ignored.
# So setting mode = 0666 for now.
SUBSYSTEM=="tty", ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6001", ATTRS{serial}=="kobuki*", MODE:="0666", GROUP:="dialout", SYMLINK+="kobuki"
# Bluetooth module
#SUBSYSTEM=="tty", ATTRS{address}=="00:00:00:41:48:22", MODE:="0666", GROUP:="dialout", SYMLINK+="kobuki"
```

**Comment by yhju** [comment]
And run below commands to restart udev service:

```
sudo service udev reload
sudo service udev restart
```

**Comment by yhju** [comment]
Sorry, above commands are not working. 
You should reboot the netbook.

**Comment by stonier** [comment]
Probably need to pull and replug the usb cable young hoon.

Is the conclusion...we need to comment the bluetooth module?

**Comment by stonier** [comment]
just to confirm, is the kobuki node crash and the bluetooth rule 100% related?

**Comment by yhju** [comment]
I sent an email for more detailed explanation. Here is brief answer.

Yes, It is related to the bluetooth rule under the certain condition. 
That is correlated with `/etc/bluetooth/rfcomm.conf` setup.

I want to suggest to comment it.

**Comment by stonier** [comment]
606b8b9434ce501ff663e9252f5459eb9c50c6af
