### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#226]
Mirza (willow) was looking over the kobuki_driver/kobuki_node code and expressed concern that he didn't see any data protection (mutexes) in a multi-threaded program.

Let's do a quick paired (2 people) code review on kobuki_driver and kobuki_node.

**Comment by bit-pirate** [comment]
Mhm, mutexes ... I'm ready to add some deadlocks! :-)

**Comment by stonier** [comment]
Ok, dug through the big picture for kobuki_node + kobuki_driver. One fix we need is in #239. Very unlikely, but fix this one for groovy.

**Comment by yhju** [comment]
![Whiteboad 0228](http://files.yujinrobot.com/images/whiteboard/whiteboard_0228.jpg)

**Comment by stonier** [comment]
The rest of kobuki_node should be fine...but. This is good for kobuki node but the current setup is fraught with danger for developers working on top of kobuki driver.

Kobuki node is ok because it all getXXX kobuki diff driver commands are all called in the slots, which are really nicely executed in sequence strictly inside the kobuki spin loop (**yeah - BLACK MAGIC!!**)

If any of these calls were being made outside the slot callbacks, then we have no guarantee of safety.

**Action** : we need to protect these calls with mutexes inside the kobuki driver.
