### ISSUE TITLE
Battery Data

### ISSUE THREAD

**Issue by teichel1** [yujinrobot/kobuki#228]
Need to be able to read the current draw from the battery using kobuki_driver. I know that the dashboard in ROS gives some data and you can see the current draw of each wheel but i would like to read it for everything, just the draw from the battery.

Thanks for any help,
Teichel1

**Comment by stonier** [comment]
@yhju is this possible?

**Comment by stonier** [comment]
Just talked to young hoon and the hardware guys. 

Apparently we have a circuit to measure the charging current, but don't have the same circuit for measuring the current draw. So we won't be able to do this without a hardware modification.

We'll keep this in mind if we upgrade the kobuki mainboard in the future.

**Comment by teichel1** [comment]
Since I cannot measure current through the kobuki driver than i will be doing it some other way. This isn't an issue but does anyone know where i can find out the make, model, specs of the motors in the kobuki i cant seem to find anything online and i am trying to avoid taking my kobuki apart. Thanks.

Teichel1

**Comment by stonier** [comment]
We can certainly supply that, I'll get the hardware guys to deliver and post something on the website.

Are you on kobuki-users@googlegroups.com?

**Comment by teichel1** [comment]
Yes i am. Teichel1 on kobuki-users. Thank you.
