### ISSUE TITLE
Kobuki driver needs auto docking

### ISSUE THREAD

**Issue by teichel1** [yujinrobot/kobuki#229]
There should be an auto-docking program with the other test programs in kobuki driver for those of us that are not using ROS.

**Comment by mirzashah** [comment]
I would love this as well, I noticed a nodelet exists for this but it would be nice if the pure C++ driver could also handle it.

**Comment by stonier** [comment]
Shouldn't be too hard to split the algorithm and the nodelet into two packages. Although this probably isn't a priority.

Also note, this is only a very simple docking algorithm that is intended as a starting point for people to write their own.

**Comment by stonier** [comment]
@teichel1 Is the DockDrive class (dock_drive.hpp and dock_drive.cpp) on its own enough for your purposes? It is the strictly c++ non-ros part of the algorithm.

If so, we can split this into its own package (or put the ros parts of auto_docking into kobuki_node).

**Comment by teichel1** [comment]
That should work just fine.

**Comment by teichel1** [comment]
I have to say that i am impressed with the quick responses and effectiveness of this of this issues page. One of the best i have run across.

**Comment by stonier** [comment]
Leaving this open for now - at a minimum, we should split the ros and non-ros parts into separate libraries in this package. I'll close it once we do that.

**Comment by stonier** [comment]
Move this library into the kobuki driver package when I do the stack split #232.

**Comment by stonier** [comment]
https://github.com/yujinrobot/kobuki_core/commit/4f41ae0bff266cbb127e1fb04923c59c0ea2645e
