### ISSUE TITLE
Kobuki auto docking fails on catkinized kobuki

### ISSUE THREAD

**Issue by corot** [yujinrobot/kobuki#234]
Error log:
Warning: class_loader::class_loader_private: SEVERE WARNING!!! A namespace collision has occured with plugin factory for class (null). New factory will OVERWRITE existing one. This situation occurs when libraries containing plugins are directly linked against an executable (the one running right now generating this message). Please separate plugins out into their own library or just don't link against the library and use either class_loader::ClassLoader/MultiLibraryClassLoader to open.
         at line 180 in /opt/ros/groovy/include/class_loader/class_loader_core.h
/opt/ros/groovy/lib/nodelet/nodelet: symbol lookup error: /opt/ros/groovy/lib/libkobuki_auto_docking_ros.so: undefined symbol: _ZN9actionlib15GoalIDGeneratorC1Ev
[kobuki-2] process has died [pid 13797, exit code 127, cmd /opt/ros/groovy/lib/nodelet/nodelet manager __name:=kobuki __log:=/home/yujin/.ros/log/c8ddd900-7f03-11e2-b697-7ce9d3ed04c2/kobuki-2.log].
log file: /home/yujin/.ros/log/c8ddd900-7f03-11e2-b697-7ce9d3ed04c2/kobuki-2*.log
[ INFO] [1361766700.516534844]: Bond broken, exiting

**Comment by tlau** [comment]
I started seeing this error recently (in the past few days) using the latest version of ROS groovy and kobuki_auto_docking from the repositories. Any ideas how to get it working again?

**Comment by stonier** [comment]
Exact same error, i.e. undefined symbols for actionlib?

**Comment by tlau** [comment]
Exact same error. In fact I found this issue by googling for "_ZN9actionlib15GoalIDGeneratorC1Ev".

**Comment by adamantivm** [comment]
Here is a complete console output from the issue @tlau is mentioning. We would greatly appreciate guidance on how to get this working again:

```
process[dock_drive_manager-1]: started with pid [2895]
process[dock_drive-2]: started with pid [2896]
Warning: class_loader::class_loader_private: SEVERE WARNING!!! A namespace collision has occured with plugin factory for class (null). New factory will OVERWRITE existing one. This situation occurs when libraries containing plugins are directly linked against an executable (the one running right now generating this message). Please separate plugins out into their own library or just don't link against the library and use either class_loader::ClassLoader/MultiLibraryClassLoader to open.
         at line 180 in /opt/ros/groovy/include/class_loader/class_loader_core.h
/opt/ros/groovy/lib/nodelet/nodelet: symbol lookup error: /opt/ros/groovy/lib/libkobuki_auto_docking_ros.so: undefined symbol: _ZN9actionlib15GoalIDGeneratorC1Ev
[FATAL] [1366036665.572599039]: Service call failed!
[dock_drive_manager-1] process has died [pid 2895, exit code 127, cmd /opt/ros/groovy/lib/nodelet/nodelet manager __name:=dock_drive_manager __log:=/home/turtlebot/.ros/log/2cc33efa-a5d9-11e2-9d85-485d607558b7/dock_drive_manager-1.log].
log file: /home/turtlebot/.ros/log/2cc33efa-a5d9-11e2-9d85-485d607558b7/dock_drive_manager-1*.log
[dock_drive-2] process has died [pid 2896, exit code 255, cmd /opt/ros/groovy/lib/nodelet/nodelet load kobuki_auto_docking/AutoDockingNodelet dock_drive_manager dock_drive/odom:=odom dock_drive/core:=mobile_base/sensors/core dock_drive/dock_ir:=mobile_base/sensors/dock_ir dock_drive/motor_power:=mobile_base/commands/motor_power dock_drive/velocity:=mobile_base/commands/velocity __name:=dock_drive __log:=/home/turtlebot/.ros/log/2cc33efa-a5d9-11e2-9d85-485d607558b7/dock_drive-2.log].
log file: /home/turtlebot/.ros/log/2cc33efa-a5d9-11e2-9d85-485d607558b7/dock_drive-2*.log
all processes on machine have died, roslaunch will exit
```

**Comment by bit-pirate** [comment]
I wonder if that error is linked to the warning occurring before:

`Warning: class_loader::class_loader_private: SEVERE WARNING!!! A namespace collision has occured with plugin factory for class (null). New factory will OVERWRITE existing one. This situation occurs when libraries containing plugins are directly linked against an executable (the one running right now generating this message). Please separate plugins out into their own library or just don't link against the library and use either class_loader::ClassLoader/MultiLibraryClassLoader to open.
         at line 180 in /opt/ros/groovy/include/class_loader/class_loader_core.h`

I haven't seen this one before. I think we are doing what they don't want us to do, but I also don't know this classloader library ...

**Comment by adamantivm** [comment]
Turns out that building from latest source fixes the issue, so I guess all we have here is just a confirmation the fix on this ticket does indeed work. 
I hope this makes it into public debians soon!

**Comment by stonier** [comment]
Great. I was just going to ask if you were using the latest source from Jorge (corot's fix). Worked for me this morning as well.

I'm re-releasing kobuki debs now once I do some testing, so you should be able to grab them from shadow-fixed shortly, or wait for the next public push.

**Comment by carolineQ** [comment]
Hi !
I have the same problem than you, which version of the code did you use to solve it ? I tried to take the latest version from the git repository but it doesn't seem to work (I used rosws).

**Comment by adamantivm** [comment]
@carolineQ: It was whatever version was in groovy-devel at that time. I unfortunately don't have the same set-up anymore to try. I guess what you could do is to check what wast he commit version number at groovy-devel 22 days ago and try with that. Sorry I can't be more specific.

**Comment by stonier** [comment]
@carolineQ What didn't work for you? Did you get it compiling? You should actually be using wstool with the kobuki stack as per the instructions [here](http://ros.org/wiki/turtlebot/Tutorials/groovy/Installation).

I also noticed tully is pushing groovy debs to public again this week, so the updates should be there once they land. You can also test out new code from debs in shadow-fixed rather than public.

**Comment by carolineQ** [comment]
Thanks for your answers, as stonier said the new debs are now public, so I updated the packages and it works now. Thanks.
