### ISSUE TITLE
Reduce the distance for detecting cliffs

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/kobuki#236]
Recent tests showed, that our cliff detection distance is around 8cm and while this is fine for Kobuki, it can cause TurtleBot to tip over. The distance is currently set in the firmware. 

I suggest lowering the distance (e.g. 4cm like Arte is currently using) and/or make this parameter configureable in the driver code.

**Comment by stonier** [comment]
Bundled with #237
