### ISSUE TITLE
Cliff Sensor Modifications

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/kobuki#237]
**Conversion**

Currently Kobuki outputs a human-_un_friendly measurement for the distance to the floor in case a cliff is detected (see kobuki_msgs/CliffEvent -> bottom).

The current output is the A/D-value of the sensor (Integer, 0 - 4095) and doesn't allow the users to related to an actual distance (e.g. in meters).

I suggest we add a conversion to the driver to output the mesured distance in meter.

**Threshold**

Currently thresholded at 8cm in firmware, too much for turtlebot. 4cm better.

**Comment by corot** [comment]
And maybe also reduce the cliff threshold from 8 to 4 cm, as Kwon proposes.

**Comment by stonier** [comment]
- Conversion : put a lookup table in kobuki driver and publish both analog and converted values (converted will lose accuracy)

**Comment by stonier** [comment]
Moved to https://github.com/yujinrobot/kobuki_core/issues/6
