### ISSUE TITLE
minimal.launch failed from kobuki_node

### ISSUE THREAD

**Issue by yhju** [yujinrobot/kobuki#238]
I've got below warning and errors. Where is robot description?

```
/opt/turtlebot/groovy/share/kobuki_node$ roslaunch kobuki_node minimal.launch --screen
 ...
[ INFO] [1361844812.576384760]: Initializing nodelet with 8 worker threads.
[ INFO] [1361844812.592864342]: waitForService: Service [/kobuki/load_nodelet] is now available.
[ WARN] [1361844812.765714129]: Kobuki : no robot description given on the parameter server
[ INFO] [1361844812.765987645]: Kobuki : configured for connection on device_port /dev/kobuki [/mobile_base].
[ INFO] [1361844812.766065261]: Kobuki : driver running in normal (non-simulation) mode [/mobile_base].
[ INFO] [1361844812.769053297]: Kobuki : Velocity commands timeout: 0.600000000 seconds [/mobile_base].
[ INFO] [1361844812.770995711]: Kobuki : using odom_frame [odom][/mobile_base].
[ INFO] [1361844812.772424911]: Kobuki : using base_frame [base_footprint][/mobile_base].
[ INFO] [1361844812.773935267]: Kobuki : not publishing transforms (see robot_pose_ekf) [/mobile_base].
[ERROR] [1361844812.777314121]: Kobuki : initialisation failed [/mobile_base].
[ERROR] [1361844812.777491038]: Kobuki : could not initialise! Please restart.
```

minimal.launch from turtlebot_bringup was fine.

**Comment by stonier** [comment]
kobuki_description is in its own stack now (rest of kobuki catkinized, kobuki_description could not because of xacro) - did you install that?

**Comment by stonier** [comment]
hmm, if turtlebot started fine...then something else is up.

Ask jorge, he was starting the kobuki_node yesterday.

**Comment by corot** [comment]
All is ok; minimal.launch do not load robot description, so we cannot visualize the robot. Make sense, as we want just the mobile base up and running, nothing more.

With turtlebot_minimal.launch we do, however, so we can visualize the robot.

**Comment by yhju** [comment]
OK, rest two errors were my fault. I launched kobuki_node from netbook's local terminal yesterday and not killed it. 

So, robot_description param warning is not related to this errors. And warning message is normal and intended for kobuki, even though turtlebot have that param by default.

Thanks.

**Comment by yhju** [comment]
kobuki_node and kobuki_driver already have exception mechanism for device open error. Don't know why initialization has failed.

**Comment by meitiever** [comment]
sudo chmod 776 /dev/ttyUSB0
solve the problem.
