### ISSUE TITLE
Race condition in base control setting/getting

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#239]
One possible place for a race condition is in the diff drive setting of velocity commands and getting of velocity commands. The kobuki_node sets in the ros callback thread, and gets in the kobuki spin thread as its about to write to the firmware. Fix this one for groovy.

Refer to #226.

**Comment by yhju** [comment]
Fixed by b9b82e53493c6bda4d3ef395ce722fe6bec5a56e.
Tested and reviewed.
Done.
