### ISSUE TITLE
Protect public driver calls

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#240]
All of the getXXX functions need to be protected against people calling them whilst in the middle of a sensitive part of the spin loop.

Not urgent for a bugfix release and we really need to test thoroughly after mutexin'g everywhere. 

Our kobuki node is fine because we use liberal doses of black magic by calling these functions only in the slot callbacks...and these are nicely sequentially called in the kobuki spin function.

But this is important for people building their own programs on top of kobuki driver. Target for hydro.

Refer to #226.

**Comment by mirzashah** [comment]
@stonier @yhju 
Hey guys, I saw the comments from the closed "Code Review" issue. Just to clarify,  my concern wasn't so much that a multi-threaded program using the driver was going to have a problem (though that's still a concern), but rather that it's not correctly implemented even for a single threaded program. 

I may be using it wrong or misunderstanding the code, but when you call init(), it spawns a thread which is updating member variables in the Kobuki class. Any code that's using the driver, even if single threaded, is going to asynchronously be calling the get*() methods. However, when I looked at the code, I noticed no protection was being used by the spin() (the thread entry method) when updating those members. That's what seemed incorrect to me. 

In my code, I don't use any of the ecl sigslots stuff that you guys use in your example. I have a loop in a single-threaded program that polls the sensors via the get*() calls, then calls updateOdometry to get updated odometry, and then repeats that indefinitely. So far it seems to work fine, so it may be a non-issue.

**Comment by stonier** [comment]
I believe we're on the same page here Mirza.

The kobuki node program doesn't calls the get*() functions asynchronously - rather it does that from within the slot callbacks. Those callbacks are run from _inside_ that thread spawned by init - so no problem there as it lines up all the writing and reading sequentially. But its dangerous code as soon as someone starts calling those getXXX functions asynchronously, like you have done with a polling method (multi threaded or single threaded).

We didn't want to possibly introduce a messy bug fixing/cleaning it up for groovy, but if you are having problems, we can bump up the priority. Otherwise we'll implement in-house and test in various demos going towards hydro.

Horrible spaghetti code...done by three or four developers used for ad-hoc projects over a few years. Would be nice to redesign/rewrite it properly, but hard to justify the time if it's working.

**Comment by mirzashah** [comment]
I don't think it's too terribly difficult to fix, it just requires the use of a mutex by spin() and all the getters. I'm going to add that in myself if you don't get a chance to get to it...when I do I'll make a pull request if it hasn't been patched. I'll make sure to use an ecl mutex.

**Comment by stonier** [comment]
Yeah, I know. A pull request would be great if we don't get around to it before you do.

**Comment by stonier** [comment]
Mutex protection is in hydro. I'll just check that we have a synchronous way of accessing the bundle of sensor data at one time so it's all synchronised.

3c4c399a460b314152722de6b99804e138d68e88

Its fugly - user should take care of locking and unlocking around his getXXX calls. This ensures that the data is all synchronised. ugh...spaghetti :spaghetti: !
