### ISSUE TITLE
Convert firmware changelog to markdown format.

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#241]
Just check for broken links. Definitely
- files.yujinrobot.com

Maybe:
- kobuki.yujinrobot.com
- roswiki for kobuki stack
- online guide

**Comment by yhju** [comment]
Converted and updated [here](https://github.com/yujinrobot/kobuki/blob/19393e173b65be3cd9a1b00f1f959f7880757b5e/kobuki_driver/firmware_changelog.md).
And also checked all above sites.
Done.
