### ISSUE TITLE
Packet Integrity Check

### ISSUE THREAD

**Issue by yhju** [yujinrobot/kobuki#245]
Actual implementation to prevent communication failure due to malformed bytestream.

**Comment by stonier** [comment]
What are you thinking about here YH? I haven't been able to think up any improvements on this one.

**Comment by stonier** [comment]
Follow this up and close it.

**Comment by yhju** [comment]
Done by 4648538d54ff58952d8124f6e3f953c76a181416.

**Comment by yhju** [comment]
found another place for improvements

**Comment by yhju** [comment]
Done.

**Comment by stonier** [comment]
This a relatively large commit - can you briefly explain what you did here?

Was there also a second commit? If so, link it.

**Comment by yhju** [comment]
All related commits are already listed in this page.

9 month ago, I added length field in sub-payload of protocol for compatibility among various firmware - driver pairs. Issue #168.

But, driver was not actually using it in packet validation. There was also no actual exception handling on validation failure, when packet class return false on [deserialize call](https://github.com/yujinrobot/kobuki/blob/535fc22266fa5bde734b07eb5dc09f786d0319ef/kobuki_driver/src/driver/kobuki.cpp#L265), such as removing malformed sub-payload. It will fall in infinite while loop.

**Commit Summary**

4648538d54ff58952d8124f6e3f953c76a181416:
- added packet validity check in each packet class.

27c62af94cd52803974676448eb4bf500d8c68ab:
- added fixPayload function, by moving code of default case in packet parsing.
- when packet class return false on deserialize call, fixPayload will actually fix it.
- added getPayload function on packet_handler that provide just payload only, except header, length field of payload, and checksum for more clear packet parsing and processing.

**Comment by stonier** [comment]
Ok, thanks.

Do we need to test this thoroughly next week or have you been using it for a while?

**Comment by yhju** [comment]
It is very recent commit, and I tested it shortly. We need some test.

**Comment by stonier** [comment]
I would prefer not to have critical driver functionality updates going in the day before a major release without any testing.

Would have been better more than a week ago, or delayed until some decent testing on it saw it through. We'll manage this time, but please be a bit more careful before a major product release next time.
