### ISSUE TITLE
velocity limiter on kobuki_driver

### ISSUE THREAD

**Issue by yhju** [yujinrobot/kobuki#246]
conversion logic in diff_drive module has a crack. 

When diff_drive module receive the command velocity of (10 m/s, -5 deg/s) pair, kobuki goes crazy backward.

**Comment by stonier** [comment]
Follow this up and make sure it is closed.

**Comment by yhju** [comment]
Resolved by 1c141a54fb2c0e2ec453b32f8026d1cd0ffb14d9
