### ISSUE TITLE
[Feature Req]ROS msg for analog input

### ISSUE THREAD

**Issue by jihoonl** [yujinrobot/kobuki#248]
there is only digital input. :(

```
/mobile_base/commands/digital_output
/mobile_base/commands/external_power
/mobile_base/commands/led1
/mobile_base/commands/led2
/mobile_base/commands/motor_power
/mobile_base/commands/reset_odometry
/mobile_base/commands/sound
/mobile_base/commands/velocity
/mobile_base/debug/raw_data_command
/mobile_base/debug/raw_data_stream
/mobile_base/events/bumper
/mobile_base/events/button
/mobile_base/events/cliff
/mobile_base/events/digital_input
/mobile_base/events/power_system
/mobile_base/events/robot_state
/mobile_base/events/wheel_drop
/mobile_base/sensors/bumper_pointcloud
/mobile_base/sensors/core
/mobile_base/sensors/dock_ir
/mobile_base/sensors/imu_data
/mobile_base/sensors/imu_data_raw
/mobile_base/version_info
/mobile_base_nodelet_manager/bond
```

**Comment by corot** [comment]
Are included on /mobile_base/sensors/core.
Digital input too, but I added also as events because is more convenient that check /mobile_base/sensors/core continuously.

**Comment by stonier** [comment]
Analog inputs are continuous no?

It should go in `/mobile_base/sensors` if that is the case. The events are for 'events', i.e. when there is a state change and these are usually happening rarely. Not for continuous streams of data - use the sensors for that.

It should be a lazy publisher too, i.e. check if there are subscribers before going to the effort of extracting from core and publishing.
