### ISSUE TITLE
Allow dynamically configure PID controller gains

### ISSUE THREAD

**Issue by corot** [yujinrobot/kobuki#249]
We need to change firmware, driver and node.

Don't forget a huge warning in the doc to prevent beginners to play with this!

**Comment by bit-pirate** [comment]
Why do we need this? Did you experience issues with varying loads?

**Comment by corot** [comment]
Was a Bill's suggestion. We don't need it by now, really. But is a nice feature for advanced users. For example to climb slopes, haul heavy loads or simply customize robot operation.

**Comment by corot** [comment]
Btw, my robot provides it and is much crappier than kobuki!

**Comment by bit-pirate** [comment]
Are you trying to tease us?

2013/5/22 corot notifications@github.com

> Btw, my robot provides it and is much crappier than kobuki!
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/yujinrobot/kobuki/issues/249#issuecomment-18258823
> .

## 

Marcus Liebhardt
Adresse: Zimmer 403, 634-1 Seongsan-dong, Mapo-gu, 121-846, Seoul, Republik
Korea
Address: Room 403, 634-1 Seongsan-dong, Mapo-gu, 121-846, Seoul, Republic
of Korea
주소: 대한민국 서울특별시 121-846 마포구 634-1 성산동 4 층 403 호
Mobile / Mobilfunk: +82 10 3322 0566
Email: ich@marcusliebhardt.de ich@marcusliebhardt.de

**Comment by stonier** [comment]
Another idea, have split pid's in the robot, on for low speeds, another for high speeds.

Actually maybe not such a great idea, it's the payload that causes the problems. PID's for kobuki are currently well tuned, for turtlebot not.

**Comment by stonier** [comment]
Target:
- Just put the mechanism there, let's not worry about tuning it until we really need it (jprobably next rocon demo)
- Einstein - firmware
- Young Hoon - sofware driver and ros node parameters (needs defaults and parameter validation).

**Comment by yhju** [comment]
updating firmware protocol documentation remains.

**Comment by corot** [comment]
Also we need to check that firmware's minor version is >= 2. If not, show a warning with the Kobuki firmware updates URL.

if (firmware.check_minor_version() < 0) ....

**Comment by corot** [comment]
And add the same message in the wiki!

**Comment by stonier** [comment]
Also add notes on the wiki and in the doxygen specifying what the default values are so people have a reference point for experimentation.

**Comment by yhju** [comment]
Factory default value of PID gains added on doxygen by 3a0bf5e8a17bf82acbd70d14258961e52727216c.
ROS wiki is not editable yet.

**Comment by yhju** [comment]
Version of updated firmware is 1.2.0. It is not released yet on [http://files.yujinrobot.com/kobuki/firmware](http://files.yujinrobot.com/kobuki/firmware).

**Comment by yhju** [comment]
firmware released, changelog also updated.

**Comment by yhju** [comment]
roswiki also updated on http://wiki.ros.osuosl.org/kobuki_node/hydro
