### ISSUE TITLE
Releasing debs of version 3.6

### ISSUE THREAD

**Issue by ablasdel** [yujinrobot/kobuki#250]
This discussion came up last month: https://mail.google.com/mail/u/0/?shva=1#apps/kobuki/13d8baa7ae4e5d2a

The debs are still built from 3.5 but everything seems to have been bloomed for 3.6

The version number needs to be changed in this file:
https://github.com/ros/rosdistro/blob/master/releases/groovy.yaml

**Comment by stonier** [comment]
Sorry - @Jorge got really busy on another job.

I think I need to do a quick check over all the stacks (some synchronisation issues and going to have to check that kobuki works with the new bloom anyway) so I'll run through some pre-releases, blooming and update them all as necessary on Sunday/Monday.

**Comment by ablasdel** [comment]
Not a problem. We just ran into an issue and had to build from source and
noticed the debs were still old

**Comment by stonier** [comment]
[Version 3.7](https://github.com/ros/rosdistro/pull/704) is in the pipeline.
