### ISSUE TITLE
Reconsider enable/disable motors functionality

### ISSUE THREAD

**Issue by corot** [yujinrobot/kobuki#253]
As we are not really ppwering on/off the motors, but just inhibiting commands to the mobile base, I wonder whether this functionality just adding noise and confusion.

More important problem is that there aren't any feedback about the enable/disable state, so for people ignoring (or forgetting, as me) this functionality it's easy to expend time trying to realize why the robot is not moving at all.

Is it useful for someone? OR can you figure out useful use cases?

**Comment by corot** [comment]
Issue #223 talks about the same problem. Maybe we can use one of the programmable LEDs only if the user is not using them. On/off sounds are also a good addition, but is not enough because we need a permanent notification.

**Comment by stonier** [comment]
Maybe expose it in kobuki dashboard?

**Comment by stonier** [comment]
Leave this in for now - let's just make sure it gets exposed as decently as possible.
