### ISSUE TITLE
Auto-docking more flexible.

### ISSUE THREAD

**Issue by corot** [yujinrobot/kobuki#262]
Now all speeds are hardcoded, what it's ok for normal kobuki/turtlebot. But with heavier robots, as waiterbot, minimum speeds are very slow, so the robot can get stuck easily.

Allow some flexibility on its configuration, at least lower velocity limits.

**Comment by bit-pirate** [comment]
Please also make it collision-aware when it approaches the docking station, e.g. wait a bit, abort current docking and start over etc.

**Comment by corot** [comment]
Ufff...   this is not gonna happen right now, ㅋㅋㅋ.

I opened this to justify the small change I did for rocon demo. But we can keep open as a reminder of the limitations we have now.

**Comment by tulku** [comment]
Hi! I'm facing a similar issue with a heavier than usual Turtlebot. This patch https://github.com/yujinrobot/kobuki/commit/0416c81e5d08466477c5806443a580a142d0d465 would be very helpful! Do you know when this will be released in a deb?

Thanks!

**Comment by bit-pirate** [comment]
We are currently working on releases for Hydro. Maybe we can get things stuffed in for those releases?!

**Comment by tulku** [comment]
That would be great! I hope you can get these currents in the next release.

We could start using hydro as well.

**Comment by adamantivm** [comment]
Just wanted to add my vote for releasing the configuration patch as soon as reasonably possible.

**Comment by mirzashah** [comment]
:+1:  Likewise, this is a feature I would really love to have!

**Comment by bit-pirate** [comment]
What does the solution look like? Is there a plan for it being released?

**Comment by jihoonl** [comment]
The configuration patch which @corot made would be sufficient for this issue.

Do you have expected feature besides the configurable minimum speed patch?

**Comment by bit-pirate** [comment]
Please link to the patch and/or issue in order to allow others to read about what has been implemented. Thanks!

**Comment by jihoonl** [comment]
please see the ref-ed commit above.

**Comment by corot** [comment]
I think we can keep this closed until we make a full review of our algorithm, which is far from being perfect.

As we will use it in the incoming demos, probably this gonna happen quite soon.

**Comment by corot** [comment]
Confirmed that it is released on Hydro.

**Comment by bit-pirate** [comment]
> I think we can keep this closed until we make a full review of our algorithm, which is far from being perfect.

To clarify this a bit. The current version is sufficient for our needs. If other issues are found or further requirements exist, please open new issues here.
