### ISSUE TITLE
Not give a beep when uninitialized as soon as initialized.

### ISSUE THREAD

**Issue by yichoe** [yujinrobot/kobuki#270]
For hydro-devel in Windnows, Kobuki does not give a beep when we run one of sample  - demo_kobuki_initialisation.exe. 

However, Kobuki gives a beep when we add a spin function calling sleep repeatedly after initialization of Kobuki.

**Comment by stonier** [comment]
Ah, program finishes and closes the serial device before it transmits the commands in the buffer?
