### ISSUE TITLE
Fix Kobuki's inertia

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/kobuki#271]
Currently the centre of mass is assumed to be in the centre of Kobuki's volume, which is wrong (mostly due to the battery being intentionally placed at the front).

The result is that in Gazebo Kobuki is constantly bouncing from the front to the back and vice versa.

**Comment by bit-pirate** [comment]
DK is checking, if he can calculate it with their software.

**Comment by stonier** [comment]
For the approximate purposes of simulation, it would be close to being halfway from the centre to the front of the robot. If you want to save time, just do that but make sure there is a comment next to it saying this is just a rough guess, not a calculation. 

If DK can calculate quickly though, thats good.
