### ISSUE TITLE
Reset odometry does not reset to zero pose

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/kobuki#274]
Using this function does not bring odom back to zero position and rotation.

**Comment by bit-pirate** [comment]
Rotation is not reset at all and position contains an offset. Maybe that has to do with a odom initialisation problem.

**Comment by bit-pirate** [comment]
Testing again shows, that odom position is set to zero. So, the failing test might really be link to a initialisation problem. Resetting the rotation is still missing though.

**Comment by bit-pirate** [comment]
And another update: After using the robot for a while the offset in position increases.

**Comment by corot** [comment]
I didn't check the code, but I suppose that you can reset odometry (encoders) but no gyro, so position gets reset but rotation remains (as robot_pose_ekf ensures that gyro readings dominate over encoders).

Easy solution is to always subtract an offset from gyro readings, initially zero but that takes current reading with every odometry reset call.

**Comment by stonier** [comment]
Sounds like we need someone to do an experiment just to determine where the problem is first.

**Comment by stonier** [comment]
Jorge - find the root cause. If it's a software driver problem, move issue to young hoon or dan.

**Comment by corot** [comment]
I was right, reset odometry (encoders) is reseted properly, but rotation (imu) remains. The position drifts with time because it gets accumulated in the robot_pose_ekf filter.

So I will first remove robot_pose_ekf (https://github.com/yujinrobot/yujin_ocs/issues/7) and then solve this will be  easier.
