### ISSUE TITLE
Documentation Protocol Error

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#280]
Error in the protocol documentation (doxygen) that needs to be fixed. From Ryan Gariepy at Clearpath:

```
Hi Daniel,

I'm finishing up a LabVIEW implementation of a Kobuki driver and wanted to report what I believe to be an minor error in your protocol spec.

In the General Purpose Output area, you've got 0x0010 through 0x0080 to turn on relays for 3.3, 5, 12@1A, and 12@5A respectively. My tests are showing that the proper order is 5, 3.3, 12@5A, 12@1A. This doesn't seem to be used in the ROS driver, hence why it may have slipped through.

Ciao,

Ryan
```

**Comment by yhju** [comment]
I checked both firmware and hardware, and confirmed that correct order is `3.3V`, `5.0V`, `12V@5A`, `12V@1.5A`.

**Comment by yhju** [comment]
Typo corrected by 54f8d0964a51e9c9119a6e7b6f8b02b660884e0a.

Need to contact Ryan for discussion about `3.3V`, `5.0V` order.

**Comment by stonier** [comment]
Check the hardware result of turning on those relays.  Maybe wires are crossed.

**Comment by yhju** [comment]
Hardware also doubly checked.

**Comment by stonier** [comment]
Ok, good. Just cc'd you to the email thread. You can talk to him there.

**Comment by stonier** [comment]
Closing this one for now - we've checked to our satisfaction and can't find a problem. If Ryan has more information that we missed, reopen it in kobuki_core.
