### ISSUE TITLE
Doxygen Update Script/Docs

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#281]
Convenient script for uploading our doxygen to github.

Or at the very least...document the process somewhere!

**Comment by yhju** [comment]
Done by eeddc544689338113a4420e0ed7c6e8a2fa15b27 and dc130acc87a2a04fcd5c09fe6043c7dda7f70432.
First Automated Update : a4425e3266f2b89d2c05a679e1279770dea6e72e
