### ISSUE TITLE
Add bugtracker and repo info to package.xml

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/kobuki#285]
URL info like below is now parsed on the ROS wiki.

```
<url type="website">http://moveit.ros.org</url>
<url type="bugtracker">https://github.com/ros-planning/moveit_ros/issues</url>
<url type="repository">https://github.com/ros-planning/moveit_ros</url>
```

http://www.ros.org/wiki/moveit_ros?distro=hydro

Let's add this information to our packages as well.
- [x] kobuki
- [x] kobuki_arm
- [x] kobuki_auto_docking
- [x] kobuki_bumper_2_pc
- [x] kobuki_controller_tutorial
- [x] kobuki_description
- [x] kobuki_driver
- [x] kobuki_ftdi
- [x] kobuki_keyop
- [x] kobuki_node
- [x] kobuki_safety_controller
- [x] kobuki_testsuite

**Comment by bit-pirate** [comment]
Thanks @yhju !

**Comment by corot** [comment]
Let's do everywhere...
did it
