### ISSUE TITLE
Not to be confused with mayor.

### ISSUE THREAD

**Issue by yhju** [yujinrobot/kobuki#287]
https://github.com/yujinrobot/kobuki/blob/hydro-devel/kobuki_driver/include/kobuki_driver/packets/firmware.hpp#L118

**Comment by bit-pirate** [comment]
mayor? major? :-)

**Comment by yhju** [comment]
It should be major, right?

**Comment by yhju** [comment]
Done by d5fda9ffd9782f94a65ddf7346778300416ef87e and d5fda9ffd9782f94a65ddf7346778300416ef87e.
