### ISSUE TITLE
Bump minor version on driver and increase the current firmware version

### ISSUE THREAD

**Issue by corot** [yujinrobot/kobuki#289]
Due to issue #249. 

CURRENT_FIRMWARE_MINOR_VERSION changes to 2.

This will make a warning log advising to update firmware at driver startup.

**Comment by corot** [comment]
Confirm that issue #249 is ok....

**Comment by stonier** [comment]
Just confirming...

This will advise on startup but not stop the program (i.e. just ROS_INFO/ROS_WARN or something?).

Was this the behaviour of existing code?

**Comment by corot** [comment]
As you said, you will see this warning:

```
sig_warn.emit("Robot firmware is outdated; we suggest you to upgrade it " \
                      "to benefit from the latest features. Consult how-to on: "  \
                      "http://kobuki.yujinrobot.com/documentation/howtos/upgrading-firmware");
```

**Comment by corot** [comment]
But I will add an specific message in case you call set/get PID methods

**Comment by stonier** [comment]
Ah...we did good!
