### ISSUE TITLE
Launchers for turtlebot

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#3]
Redo the launchers, integrating them in the same style as turtlebot_bringup

**Comment by stonier** [comment]
Minimal.launch up and running apart from diagnostics.

**Comment by stonier** [comment]
kinect.launch now running.

**Comment by bit-pirate** [comment]
I think, we have all necessary launch files. The rest in turtlebot_bringup are specific sripts. Furthermore, these kind of scripts seem to be covered by issue #19. So close this issue or did I miss anything?

**Comment by stonier** [comment]
Yep, just upstart services to add now.
