### ISSUE TITLE
Kobuki : initialisation failed [/mobile_base]

### ISSUE THREAD

**Issue by redheli** [yujinrobot/kobuki#304]
Hi,

   I have a turtlebot2-kobuki with Acer Aspire One laptop. 
   and installed ubuntu 12.04 in laptop.
when I run " roslaunch kobuki_node minimal.launch" , no error info.  but no data publish by kobuki node. 
   when try to kill the process,ctrl+c, get error info: 
[ERROR] [1379337100.557846797]: Kobuki : initialisation failed [/mobile_base].
[ERROR] [1379337100.558034818]: Kobuki : could not initialise! Please restart.

I find similar issue below,but no solution.
http://answers.ros.org/question/52203/kobuki-malformed-subpayload/

anyone can help?

turtlebot@turtlebot-AO756:~$ roslaunch kobuki_node minimal.launch 
... logging to /home/turtlebot/.ros/log/df0dba52-1ecb-11e3-9e04-844bf57e1339/roslaunch-turtlebot-AO756-10293.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://turtlebot-AO756:43969/
# SUMMARY

PARAMETERS
- /diagnostic_aggregator/analyzers/input_ports/contains
- /diagnostic_aggregator/analyzers/input_ports/path
- /diagnostic_aggregator/analyzers/input_ports/remove_prefix
- /diagnostic_aggregator/analyzers/input_ports/timeout
- /diagnostic_aggregator/analyzers/input_ports/type
- /diagnostic_aggregator/analyzers/kobuki/contains
- /diagnostic_aggregator/analyzers/kobuki/path
- /diagnostic_aggregator/analyzers/kobuki/remove_prefix
- /diagnostic_aggregator/analyzers/kobuki/timeout
- /diagnostic_aggregator/analyzers/kobuki/type
- /diagnostic_aggregator/analyzers/power/contains
- /diagnostic_aggregator/analyzers/power/path
- /diagnostic_aggregator/analyzers/power/remove_prefix
- /diagnostic_aggregator/analyzers/power/timeout
- /diagnostic_aggregator/analyzers/power/type
- /diagnostic_aggregator/analyzers/sensors/contains
- /diagnostic_aggregator/analyzers/sensors/path
- /diagnostic_aggregator/analyzers/sensors/remove_prefix
- /diagnostic_aggregator/analyzers/sensors/timeout
- /diagnostic_aggregator/analyzers/sensors/type
- /diagnostic_aggregator/base_path
- /diagnostic_aggregator/pub_rate
- /mobile_base/base_frame
- /mobile_base/battery_capacity
- /mobile_base/battery_dangerous
- /mobile_base/battery_low
- /mobile_base/cmd_vel_timeout
- /mobile_base/device_port
- /mobile_base/odom_frame
- /mobile_base/publish_tf
- /mobile_base/wheel_left_joint_name
- /mobile_base/wheel_right_joint_name
- /rosdistro
- /rosversion

NODES
  /
    diagnostic_aggregator (diagnostic_aggregator/aggregator_node)
    mobile_base (nodelet/nodelet)
    mobile_base_nodelet_manager (nodelet/nodelet)

ROS_MASTER_URI=http://192.168.1.6:11311

core service [/rosout] found
process[mobile_base_nodelet_manager-1]: started with pid [10311]
process[mobile_base-2]: started with pid [10312]
process[diagnostic_aggregator-3]: started with pid [10344]
^C[diagnostic_aggregator-3] killing on exit
[mobile_base-2] killing on exit
[mobile_base_nodelet_manager-1] killing on exit
[ERROR] [1379337100.557846797]: Kobuki : initialisation failed [/mobile_base].
[ERROR] [1379337100.558034818]: Kobuki : could not initialise! Please restart.
shutting down processing monitor...
... shutting down processing monitor complete
done

syslog when plugin the usb cable:

Sep 16 21:27:29 turtlebot-AO756 kernel: [ 4110.303988] usb 2-1.4: USB disconnect, device number 21
Sep 16 21:27:30 turtlebot-AO756 kernel: [ 4110.519943] usb 2-1.4: new low-speed USB device number 23 using ehci-pci
Sep 16 21:27:30 turtlebot-AO756 kernel: [ 4110.618532] usb 2-1.4: New USB device found, idVendor=093a, idProduct=2500
Sep 16 21:27:30 turtlebot-AO756 kernel: [ 4110.618543] usb 2-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Sep 16 21:27:30 turtlebot-AO756 kernel: [ 4110.618549] usb 2-1.4: Product: USB OPTICAL MOUSE
Sep 16 21:27:30 turtlebot-AO756 kernel: [ 4110.618554] usb 2-1.4: Manufacturer: PIXART
Sep 16 21:27:30 turtlebot-AO756 kernel: [ 4110.625509] input: PIXART USB OPTICAL MOUSE as /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.4/2-1.4:1.0/input/input15
Sep 16 21:27:30 turtlebot-AO756 kernel: [ 4110.625735] hid-generic 0003:093A:2500.0003: input,hidraw0: USB HID v1.10 Mouse [PIXART USB OPTICAL MOUSE] on usb-0000:00:1d.0-1.4/input0
Sep 16 21:27:30 turtlebot-AO756 mtp-probe: checking bus 2, device 23: "/sys/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.4"
Sep 16 21:27:30 turtlebot-AO756 mtp-probe: bus: 2, device: 23 was not an MTP device
Sep 16 21:27:30 turtlebot-AO756 kernel: [ 4111.015758] usb 2-1.2: new full-speed USB device number 24 using ehci-pci
Sep 16 21:27:30 turtlebot-AO756 kernel: [ 4111.116048] usb 2-1.2: New USB device found, idVendor=0403, idProduct=6001
Sep 16 21:27:30 turtlebot-AO756 kernel: [ 4111.116059] usb 2-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Sep 16 21:27:30 turtlebot-AO756 kernel: [ 4111.116065] usb 2-1.2: Product: iClebo Kobuki
Sep 16 21:27:30 turtlebot-AO756 kernel: [ 4111.116071] usb 2-1.2: Manufacturer: Yujin Robot
Sep 16 21:27:30 turtlebot-AO756 kernel: [ 4111.116075] usb 2-1.2: SerialNumber: kobuki_A601D9OE
Sep 16 21:27:30 turtlebot-AO756 kernel: [ 4111.118645] ftdi_sio 2-1.2:1.0: FTDI USB Serial Device converter detected
Sep 16 21:27:30 turtlebot-AO756 kernel: [ 4111.118712] usb 2-1.2: Detected FT232RL
Sep 16 21:27:30 turtlebot-AO756 kernel: [ 4111.118718] usb 2-1.2: Number of endpoints 2
Sep 16 21:27:30 turtlebot-AO756 kernel: [ 4111.118723] usb 2-1.2: Endpoint 1 MaxPacketSize 64
Sep 16 21:27:30 turtlebot-AO756 kernel: [ 4111.118728] usb 2-1.2: Endpoint 2 MaxPacketSize 64
Sep 16 21:27:30 turtlebot-AO756 kernel: [ 4111.118733] usb 2-1.2: Setting MaxPacketSize 64
Sep 16 21:27:30 turtlebot-AO756 kernel: [ 4111.119080] usb 2-1.2: FTDI USB Serial Device converter now attached to ttyUSB0
Sep 16 21:27:30 turtlebot-AO756 mtp-probe: checking bus 2, device 24: "/sys/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.2"
Sep 16 21:27:30 turtlebot-AO756 mtp-probe: bus: 2, device: 24 was not an MTP device

**Comment by bit-pirate** [comment]
Hi redheli!
Usage questions and issues like this are better asked on ROS Answers. Once we know, there is specific bug, feel  free to post it here. Could you ask your question again on ROS Answers? Please also add what code you use - ROS distro, debs or source - and if you are running a 32 or 64bit system. And last, but not least, please post the log ouput shown when using the `--screen` option for roslaunch. Thanks!
