### ISSUE TITLE
dock_ir_link in robot description

### ISSUE THREAD

**Issue by jihoonl** [yujinrobot/kobuki#308]
I just noticed that dock ir data(/mobile_base/sensors/dock_ir) is published with dock_ir_link frame id.

But kobuki robot_description does not provide dock_ir_link.

Does anybody know about it?

**Comment by corot** [comment]
dock_ir information only tell you in which region you are, so a reference frame has no meaning. You can happily ignore it.

**Comment by jihoonl** [comment]
Ok.
