### ISSUE TITLE
improve auto dock behavior

### ISSUE THREAD

**Issue by jihoonl** [yujinrobot/kobuki#309]
The current auto docking algorithms make the initial spin to detect even if the docking station is right in front of the robot. We would like to avoid this initial spin as much as we can.

**Comment by jihoonl** [comment]
Some refactoring job is finished to prepare future upgrades. more descriptive states. Restructuring state transition.

There isn't big algorithmic improvement though.

**Comment by stonier** [comment]
Did it remove the initial spin problem you identified?

**Comment by jihoonl** [comment]
Ah I couldn't remove the initial spin. It is necessary to locate the dock. However, it does less spin than before. I will leave this issue open until the result seems significantly improved.

**Comment by stonier** [comment]
What kind of improvement? 

Does it use an educated guess to locate the dock? i.e. if it knows where it is on the map and where the dock should be....

**Comment by jihoonl** [comment]
It is pure IR-based docking algorithm improvements. I restructured the code and changed some state machines to work better if robot is near dock station. 

AR marker based docking algorithm for demo is different.  Since @corot's awesome waiterbot logic locates the robot in front of dock, I didn't see the reason to implement the ar based docking algorithm yet.

**Comment by stonier** [comment]
Was just wondering if you could seed the docking algorithm with an initial relative pose (just like you do the navi stack). That seed could come from ar marker relative poses, amcl/annotation localisation calculations...

And if there's no seed, it could fall back to it's dizzy blonde spin behaviour.

**Comment by jihoonl** [comment]
ah.. I didn't think of providing a seed to the algorithm. It is definitely helpful to avoid initial spin. I will consider it as future improvement.

**Comment by stonier** [comment]
Ok, closing this issue for now.
