### ISSUE TITLE
Add capabilites support

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/kobuki#312]

**Comment by jihoonl** [comment]
@bit-pirate is this done?

**Comment by bit-pirate** [comment]
Yes, this is done.

Starting with commit https://github.com/yujinrobot/kobuki/commit/82c1f3663e191026fef9cd53903b569f5667ba83 capabilities have incrementally been added, updated and extended. This will be work in progress until capabilities stabilise.
