### ISSUE TITLE
Move messages out of kobuki_testsuite into kobuki_messages

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#317]

**Comment by slivingston** [comment]
@stonier, should this issue be closed now that yujinrobot/kobuki_msgs#6 and #340 (of this repository) are merged?

Relatedly, [line 22 of gyro_perf.py](https://github.com/yujinrobot/kobuki/blob/0.6.5/kobuki_testsuite/scripts/gyro_perf.py#L22) should now be

``` python
from kobuki_msgs.msg import ScanAngle
```

**Comment by jihoonl** [comment]
7843e2f8894526e499ce5fb840326665ea23989f replaced  line 22 of gyro_perf.py.
