### ISSUE TITLE
Wrong scope for enum in auto_docking_ros.cpp

### ISSUE THREAD

**Issue by fuesschen** [yujinrobot/kobuki#319]
"RobotDockingState::DONE" is used which must be "DockDrive::DONE" in line 142

**Comment by jihoonl** [comment]
auto docking algorithm has been changed from hydro branch to hydro-devel branch.

DockDrive states are in hydro branch and RobotDockingState states are in hydro-devel. You might want to make both kobuki_core and kobuki branch hydro or hydro-devel for compatible implementation.
