### ISSUE TITLE
indigo release

### ISSUE THREAD

**Issue by jihoonl** [yujinrobot/kobuki#329]
What would be remain jobs?

**Comment by stonier** [comment]
- Making sure capabilities is in exactly the right shape for turtlebot
- gazebo?

**Comment by jihoonl** [comment]
How do I check whether capabilities are in the right shape?

**Comment by jihoonl** [comment]
Confirmed that gazebo works fine. @stonier might want to review [this PR](https://github.com/yujinrobot/kobuki_desktop/pull/30) in kobuki_desktop

**Comment by jihoonl** [comment]
_Release list_
- [x] kobuki_msgs
- [x] kobuki_core
- [x] kobuki
- [x] kobuki_desktop
- [x] kobuki_soft

**Comment by jihoonl** [comment]
1. Releasing kobuki_msgs, kobuki_core first.
2. Release kobuki after resolving kobuki_capabilities issue.
3. Release kobuki_desktop after checking gazebo.

**Comment by jihoonl** [comment]
@bit-pirate Can you check whether capabilities are correctly set? We need to resolve #331 as well.

**Comment by bit-pirate** [comment]
I have updates to the kobuki capabilities, which I initially intended to merge into hydro-devel. Should I do that and you later pull those changes into indigo or shall I create the PR against indigo right away?

**Comment by jihoonl** [comment]
We plan to sync hydro-devel and indigo for a while. Merge changes into hydro-devel and let me know. I hope the change also fixes circular dependency described in #331

**Comment by jihoonl** [comment]
Kobuki desktop cannot be released until we fix https://github.com/yujinrobot/kobuki_desktop/issues/33.

rqt_plot api has been changed and qtestsuite does not work now..

**Comment by jihoonl** [comment]
All repos are now in rosdistro.

**Comment by bit-pirate** [comment]
Awesome! :yum:
