### ISSUE TITLE
Indigo doc job is failing

### ISSUE THREAD

**Issue by dirk-thomas** [yujinrobot/kobuki#330]
http://jenkins.ros.org/view/Idoc/job/doc-indigo-kobuki/4/console seems to fail due to circular dependencies.

**Comment by jihoonl** [comment]
Do you have any suggestion to find which packages are involved in circular dependencies? I was trying to read all the packages dependency list but it seems to take too long time to find out..

**Comment by stonier** [comment]
On 24 Jul 2014 11:16, "Jihoon Lee" notifications@github.com wrote:

> Do you have any suggestion to find which packages are involved in
> circular dependencies? I was trying to read all the packages dependency
> list but it seems to take too long time to find out..

Its a rosdep thing so try moving the base /opt/ros directory somewhere
temporarily, lay down a kobuki repo only source workspace and play with
rosdep.

Be nice to have a little more info from the report  but shouldnt be too
hard to discover.

**Comment by dirk-thomas** [comment]
The buildfarm now (https://github.com/ros-infrastructure/jenkins_scripts/commit/97a844da10ef77455977df902db71be0e6b77aa9) prints the used dependencies in case of that error: http://jenkins.ros.org/view/Idoc/job/doc-indigo-kobuki/7/console

**Comment by stonier** [comment]
Awesome Dirk.

Looks like kobuki node<->kobuki capabilities is your problem Jihoon.

Daniel.

On 25 July 2014 01:22, Dirk Thomas notifications@github.com wrote:

> The buildfarm now (ros-infrastructure/jenkins_scripts@aed0807
> https://github.com/ros-infrastructure/jenkins_scripts/commit/aed0807c1a9dab5ef2c9bd8c2a726a3d0296c644)
> prints the used dependencies in case of that error (the dictionary a little
> bit above the exception):
> http://jenkins.ros.org/view/Idoc/job/doc-indigo-kobuki/5/console
> 
> I expanded it into a liist - the circular dependency should be easy to
> find with that:
> kobuki_testsuite
> - kobuki_node
> - kobuki_node
>   kobuki_bumper2pc
>   *
>   kobuki
> - kobuki_auto_docking
> - kobuki_bumper2pc
> - kobuki_controller_tutorial
> - kobuki_description
> - kobuki_keyop
> - kobuki_node
> - kobuki_random_walker
> - kobuki_safety_controller
> - kobuki_testsuite
>   kobuki_description
>   *
>   kobuki_capabilities
> - kobuki_node
>   kobuki_random_walker
>   *
>   kobuki_apps
> - kobuki_auto_docking
> - kobuki_random_walker
>   kobuki_safety_controller
>   *
>   kobuki_auto_docking
>   *
>   kobuki_keyop
>   *
>   kobuki_node
> - kobuki_keyop
> - kobuki_safety_controller
> - kobuki_capabilities
> - kobuki_apps
> - kobuki_keyop
> - kobuki_safety_controller
>   kobuki_controller_tutorial
>   *
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yujinrobot/kobuki/issues/330#issuecomment-50041943.

## 

Phone : +82-10-5400-3296 (010-5400-3296)
Home: http://snorriheim.dnsdojo.com/
Yujin R&D: http://rnd.yujinrobot.com/

**Comment by jihoonl** [comment]
Thanks @dirk-thomas. The circular dependency issue will continue on #331
