### ISSUE TITLE
kobuki_node and kobuki_capabilities circular dependency

### ISSUE THREAD

**Issue by jihoonl** [yujinrobot/kobuki#331]
#330 detected circular dependency between `kobuki_node` and `kobuki_capabilities`

**Comment by jihoonl** [comment]
Both packages have launch file which reference each other.
- app_manager_with_capabilities.launch in `kobuki_node` uses kobuki_capabilities package.
- kobuki_bringup provider in `kobuki_capabilities` uses `kobuki_node` params and nodelet.

**Comment by bit-pirate** [comment]
Looks like we need to do sth with `app_manager_with_capabilities.launch`

Don't want to drop it, since the auto docking and random walker app runs with just Kobuki + rapp platform. So, I'll move that launcher to the capabilities package.

Any better idea?

**Comment by bit-pirate** [comment]
This solution is now part of PR #334.

**Comment by jihoonl** [comment]
https://github.com/yujinrobot/kobuki/commit/f95c3847d97fba46b6317e00ffd78ce352ec376f should have fixed the problem

**Comment by bit-pirate** [comment]
Aish, "solves" is not a valid keyword. "resolves" it should have been... :-)

https://help.github.com/articles/closing-issues-via-commit-messages
