### ISSUE TITLE
Warning message for not matching the topic type

### ISSUE THREAD

**Issue by robotpilot** [yujinrobot/kobuki#347]
Development environment : Ubuntu 14.04 / ROS Indigo
I run a launch file and a node below to test the kobuki.  
1. roslaunch kobuki_node minimal.launch --screen 
2. rosrun kobuki_testsuite test_external_power.py 

Then, I can test the external power function, but I see the warning message below. It is no problem to test. I just report the tiny wrong situation.

[WARN] [WallTime: 1408618292.742709] Could not process inbound connection: topic types do not match: [kobuki_msgs/ExternalPower] vs. [kobuki_msgs/DigitalOutput]{'topic': '/mobile_base/commands/external_power', 'tcp_nodelay': '0', 'md5sum': '95149d524971a4c6d19e64c827307194', 'type': 'kobuki_msgs/ExternalPower', 'callerid': '/mobile_base_nodelet_manager'}

**Comment by jihoonl** [comment]
Wow.. seems like the script was unsynced from the start. :scream_cat:
It is not tiny wrong situation.  Thanks for picking this up. @robotpilot. I will patch this later.
