### ISSUE TITLE
Compilation Error: yocs_msgs/NavigateToActionResult.h: No Such File or Directory

### ISSUE THREAD

**Issue by bradleypowers** [yujinrobot/kobuki#348]
I have a compilation error when building the kobuki package:

[ 86%] Building CXX object kobuki/kobuki_auto_docking/CMakeFiles/kobuki_auto_docking_ros.dir/src/auto_docking_ros.cpp.o
[ 87%] Generating C++ code from yocs_msgs/NavigateToActionFeedback.msg
[ 87%] Generating C++ code from yocs_msgs/Waypoint.msg
[ 87%] Built target yocs_waypoints_navi_node
[ 88%] Generating C++ code from yocs_msgs/NavigateToResult.msg
Scanning dependencies of target gazebo_ros_kobuki
[ 88%] Building CXX object kobuki_desktop/kobuki_gazebo_plugins/CMakeFiles/gazebo_ros_kobuki.dir/src/gazebo_ros_kobuki.cpp.o
[ 88%] Generating C++ code from yocs_msgs/WallList.msg
In file included from /home/bpow/turtlebot/kobuki/src/yujin_ocs/yocs_navigator/include/yocs_navigator/semantic_navigator.hpp:11:0,
                 from /home/bpow/turtlebot/kobuki/src/yujin_ocs/yocs_navigator/src/yocs_navigator/semantic_navigator.cpp:6:
/home/bpow/turtlebot/kobuki/devel/include/yocs_msgs/NavigateToAction.h:52:46: fatal error: yocs_msgs/NavigateToActionResult.h: No such file or directory
 #include <yocs_msgs/NavigateToActionResult.h>

Any ideas?

**Comment by bit-pirate** [comment]
Please provide more information about your set up. For example, which ROS version are you on? 

With regards to your error, are you using the `indigo-devel` branch of yocs_msgs? It has been out of sync with indigo (which was more recent), but was sync 3 days ago. Verify, that you have the latest commits.

**Comment by jihoonl** [comment]
Seems like yocs_navigator is missing yocs_msgs_gencpp dependency. Will patch soon.

**Comment by jihoonl** [comment]
https://github.com/yujinrobot/yujin_ocs/commit/17560e98ef751714a352a5cee403fd3eb53c9fdb This should have resolved your problem.

**Comment by jihoonl** [comment]
The same patch applied on `indigo-devel` as well https://github.com/yujinrobot/yujin_ocs/commit/17560e98ef751714a352a5cee403fd3eb53c9fdb

**Comment by bradleypowers** [comment]
Excellent, I will check it out in the morning (UTC -4) and let you know how it goes.
