### ISSUE TITLE
kobuki_testsuite failing to build due to invalid dependency kobiki_apps via kobuki_node

### ISSUE THREAD

**Issue by tfoote** [yujinrobot/kobuki#349]
It was recently moved to be kobuki_rapps

Invalid line: https://github.com/yujinrobot/kobuki/blob/indigo/kobuki_node/package.xml#L64

Renaming: https://github.com/yujinrobot/kobuki/commit/e2c9657964d8a671fafe88c2a51e46713ead8e3b

A check for similar issues would be a good idea. 

Failing job: http://jenkins.ros.org/view/IbinS64/job/ros-indigo-kobuki-testsuite_binarydeb_saucy_amd64/4/console

**Comment by jihoonl** [comment]
https://github.com/yujinrobot/kobuki/commit/5fe2e798c41a7e14c5ce44bfeae1d9884b08d0e3 This should have resolved the problem. 

I have checked all kobuki, rocon, and turtlebot packages. Thanks.
