### ISSUE TITLE
Remove ycs from CMakeLists.txt

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#35]
Scan the kobuki root CMakeLists.txt and terminate any ycs related references.

**Comment by bit-pirate** [comment]
YCS related lines have only been commented out for the case someone working on issues #4, #5 and #40 needs them temporarily.
Maybe redo CMakeLists in order to have the standard ros layout (current structure comes from ycs).

**Comment by stonier** [comment]
Done.
