### ISSUE TITLE
网站没了

### ISSUE THREAD

**Issue by bill0** [yujinrobot/kobuki#361]

**Comment by bit-pirate** [comment]
Please translate. :smile:

**Comment by bill0** [comment]
the web can`t open!(^_^),sorry, i would have thought yujin is a chinese cc.

**Comment by bill0** [comment]
http://kobuki.yujinrobot.com/

**Comment by bill0** [comment]
oh,sorry,now i know i should go out the greet world fire! thx!

**Comment by bit-pirate** [comment]
Looks like you solved the issue. :smile:

Otherwise feel free to re-open it or send us an email.
