### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by RedstoneGithub** [yujinrobot/kobuki#365]
I got an error while trying to catkin_make the Kobuki workspace within Turtlebot. The error was:

```
CMake Error at ~/turtlebot/devel/share/ecl_exceptions/cmake/ecl_exceptionsConfig.cmake:141 (message):
  Project 'kobuki_keyop' tried to find library 'ecl_exceptions'.  The library
  is neither a target nor built/installed properly.  Did you compile project
  'ecl_exceptions'? Did you find_package() it before the subdirectory
  containing its code is included?

```

Edit: I got the errors while trying to `catkin_make`

**Comment by robbiedood** [comment]
Got the same issue. For melodic version, it requires many installations in order to resolve ecl_exceptions, its dependencies and dependencies' dependencies. Fortunately, still can build kobuki for melodic. (care must be taken on using melodic branch in each git)

**Comment by stonier** [comment]
One rosdep update call on this repo in your source workspace should be all it needs, that will track down all the dependencies you need and install them via apt.
