### ISSUE TITLE
Legacy_pose2d problem

### ISSUE THREAD

**Issue by Briancbn** [yujinrobot/kobuki#369]
After I change all the legacy_pose2d to pose2d and LegacyPose2d to Pose2d can the catkin_make succeed.

**Comment by stonier** [comment]
What branch are you using?  The devel branches should already have these fixes.

**Comment by stonier** [comment]
Ah I see. You are using kobuki sources,  devel branch but are not using the ecl sources.  Those changes are  in source but not as public debs yet. 

No problems here.  Just need to either check out kobuki sources from the release branch or from prior to the latest commit hash or include the ecl sources in your workspace or an underlay. 

It will resolve naturally as soon as the latest debs roll through.
