### ISSUE TITLE
kobuki_meta -> kobuki_bringup

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#39]
Bring in line with the turtlebot naming system.

**Comment by bit-pirate** [comment]
how shall we restructure our resources folder?

**Comment by bit-pirate** [comment]
i updated the installation instructions on redmine and the jenkins projects. I hope that's all.

**Comment by stonier** [comment]
Resources folder will be fine as is for now I think as it will be a hack-a-mess for a while.
