### ISSUE TITLE
Diff Drive in ROS

### ISSUE THREAD

**Issue by zweistein** [yujinrobot/kobuki#396]
I want to control separately each wheels angular velocities in a ROS node. Is there a demo code for this case?
Can the robot motion be controlled with diff drive through ROS? Is there a demo code for diff drive in ros?

**Comment by itfanr** [comment]
I need such a demo too.

**Comment by stonier** [comment]
Sorry, the firmware protocol only accepts base velocity commands and won't be updated in the future. I agree, though. It would have been a nice feature.
