### ISSUE TITLE
remove ycs' standard_comms in kobuki_node

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/kobuki#40]
ycs' standard_comms are still used in both scripts in kobuki_node. they are also listed in the kobuki_node.hpp, but not used.

**Comment by bit-pirate** [comment]
standard_comms are listed but not used kobuki_node.hpp and arm_controller.py, but currents_interpreter.py still uses them. check if those scripts are important and fix them if necessary.

**Comment by stonier** [comment]
We'll resurrect currents_interpreter.py if we need it - young hoon was using it as an adapter between the kobuki current output and rxplot to get it in the right format.
