### ISSUE TITLE
description: wheel_radius(left) != wheel_radius(right) ?

### ISSUE THREAD

**Issue by gavanderhoorn** [yujinrobot/kobuki#400]
Not sure this matters, but it would appear the `wheel_left_link` and `wheel_right_link` have slightly different radii configured for the `collision` geometry.

Left:

https://github.com/yujinrobot/kobuki/blob/161f69310ef94d2ab7566cf085231e832b8985cf/kobuki_description/urdf/kobuki.urdf.xacro#L78

Right:

https://github.com/yujinrobot/kobuki/blob/161f69310ef94d2ab7566cf085231e832b8985cf/kobuki_description/urdf/kobuki.urdf.xacro#L106

Is this on purpose?

**Comment by corot** [comment]
mmmm......  never noticed this. I guess no.

**Comment by gavanderhoorn** [comment]
Do we know which one is the correct radius?

See also [kobuki don't go straight, get a little to the right in gazebo](https://answers.ros.org/question/338481) on ROS Answers.

**Comment by corot** [comment]
According to Kobuki Parameters (https://yujinrobot.github.io/kobuki/enAppendixKobukiParameters.html), 35 mm. But I don't have a robot with me to double check...

wow!  I was considering if that error could have any impact on Gazebo!
very good catch!

**Comment by gavanderhoorn** [comment]
Will you PR a fix, or should 'someone else' do that? :)
