### ISSUE TITLE
Can not connect to the file server to download the The Flashing Utility stm32flash-0.4.tar.gz

### ISSUE THREAD

**Issue by robbiedood** [yujinrobot/kobuki#418]
Dear kobuki friends,

We tried multiple computers, but still can not connect to the file server (http://files.yujinrobot.com/kobuki/firmware/stm32flash-0.4.tar.gz) to download the flashing utility; even can not connect to the file server: http://files.yujinrobot.com/kobuki/firmware

Was wondering if someone has the same issue. Hope it is just temporary...our location is in California, US.

-- Luke

**Comment by stonier** [comment]
You can find it at https://sourceforge.net/projects/stm32flash/files/.

Still a WIP, but rebuilding documentation while doing a ROS2 port - you can find updated notes at https://kobuki.readthedocs.io/en/devel/firmware.html#updating-firmware. Let me know if you run into any problems.

**Comment by robbiedood** [comment]
Thanks, @stonier ! Updated !
