### ISSUE TITLE
Exterminate device_nodelet

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#5]
Cant use nodelets here as the turtlebot_driver and node are rather simple - just implement as a single process.

Now we could do as multiple libs and nodelets, but that is more complicated - maybe try that later.

**Comment by bit-pirate** [comment]
I moved from nodelet to a class KobukiNode which gets instantiated in a normal ros node. I pushed the changes to an extra branch. When it runs smooth on the robot we merge it with master.
