### ISSUE TITLE
ROS indexer doesn't pick up kobuki stack

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/kobuki#53]
why?

**Comment by bit-pirate** [comment]
because the indexer still points to the rosinstall file in Daniel's repo. I sent an URL update request to Ken. I'll close this, once the indexer picks up the kobuki stack.

**Comment by bit-pirate** [comment]
because the indexer still points to the rosinstall file in Daniel's repo. I sent an URL update request to Ken. I'll close this, once the indexer picks up the kobuki stack.

**Comment by stonier** [comment]
Found

**Comment by bit-pirate** [comment]
On the wiki no package pages have been created except for kobuki_udev. Shouldn't that have been the case for the other packages too? Maybe we need to update our manifests?

**Comment by bit-pirate** [comment]
Apparently, one needs to create the package pages manually. I did that and also updated our manifests. The new information should be up on the wiki once the indexer has finished its job the next time.
