### ISSUE TITLE
Kobuki Dashboard

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#55]
Learn rosgui and create a kobuki dashboard.

**Comment by yhju** [comment]
Ok.

**Comment by stonier** [comment]
http://ros.org/wiki/rqt

Alot of the infrastructure is there.

**Comment by stonier** [comment]
See also turtlebot/turtlebot_viz/issues/1

**Comment by stonier** [comment]
Moving to the robot_dashboard prototype.

**Comment by bit-pirate** [comment]
I close this one. Follow up on: https://github.com/yujinrobot/kobuki_desktop/issues/4
