### ISSUE TITLE
Implement drive_mode

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#64]
Same as turtlebot - they have different modes of command. See http://www.ros.org/wiki/turtlebot_node

**Comment by jakan2** [comment]
It was issue when we was on design phase.
At that time, our conclusion was that 
- Robot can be charged without mode
- Robot can be work during charging
- Do not split the working mode which may be complicate to use robot at user point of view

Am i right?

**Comment by stonier** [comment]
Yep...however this issue was about the turtlebot_node doing something different at a higher level. It uses different velocity command inputs:
- usual navigation input via cmd_vel (twist)
- turtlebot simplified input (cant remember)
- create style (same as our fw - speed/radius)

**Comment by stonier** [comment]
Don't really want to do this, only do if necessary.

**Comment by stonier** [comment]
Keep it simple. Just use our api or the cmd_vel.
