### ISSUE TITLE
Battery Level Runtime Graph

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#66]
Generate a runtime graph for battery voltage levels. We need these to set the levels used to delineate the output in battery.hpp

**Comment by stonier** [comment]
There is a python program to continually rotate the kobukibot in kobuki_node/src/test/test_rotate.py.

Let's rosbag kobuki/mobile_base/sensors/core (contains the raw voltage data).

**Comment by stonier** [comment]
Also update the battery module to better reflect the current state.

**Comment by stonier** [comment]
I was asking Einstein about battery variation this morning. It can be significant, so perhaps doing the runtime test on just one battery is not sufficient. In addition, if the battery supplier should change things, or we change batteries, suddenly, everything will be different again.

Point : we probably need to be able to reproduce these runtime graphs quite often, so let's create a simple setup (scripts, launchers?) which can rosbag, then spin out a graph based on this data with the least effort. And doc it somewhere.

**Comment by corot** [comment]
We have some data:
- 4 cells battery: 4 hours, 33 minutes
- 8 cells battery: 15 hours, 48 minutes

However, during the test with the 8 cells battery, the robot was not moving for about 20 minutes.

The huge different is quite surprising... Maybe the small battery was wrong, or not 100% charged?

**Comment by stonier** [comment]
Really big difference.

What happened with the rosbag problem by the way?

Also, I think we should probably get this all configured, like a factory line, and run tests, like Einstein said, on 3 batteries of each type. Maybe we can get their iclebo test engineers to help us.

**Comment by stonier** [comment]
Talk with einstein again - lets work out a standard procedure for generating battery graphs, both via hardware and via turtlebot software.
- Try on 3x4S1P batteries, 3x 4S2P batteries.
- Document procedure : http://redmine.yujin.com/projects/kobuki/wiki/Generating_Runtime_Graphs
- Put some graphs up on kobuki web site : http://kobuki.yujinrobot.com/
- Tutorial for turtlebot users if they want to generate their own runtime graph http://ros.org/wiki/kobuki/Tutorials

**Comment by corot** [comment]
After retesting a bit more carefully:

4S1P: 4:33
4S2P: 8:54

What match really well the results from electronics team:

4S1P: 4:36
4S2P: 8:45

Also the voltage curves match almost perfectly can check both here:

   http://redmine.yujin.com/projects/kobuki/wiki/Generating_Runtime_Graphs

The huge time obtained for 4S2P in the first test was probably the result of not having the kinect running. We can ignore that result.
