### ISSUE TITLE
Sound Module

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#67]
Implement the sound module in the driver.

**Comment by jakan2** [comment]
got you. 
It would be available on Monday

**Comment by stonier** [comment]
Sound command is not yet implemented, only sound sequence.

Sound sequences:
-  0 - turning on
- 1 - turn off
- 2 - recharge start
-  3 - press button,
- 4 - error sound
- 5 - start cleaning
- 6 - cleaning end

**Comment by stonier** [comment]
5c2f8a3818b51b82faf5deff91a8455f8d6fffc9 Test finished.

Marcus!

  0x0300 != 0x03
