### ISSUE TITLE
What is cliff data?

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#69]
What is the difference between CoreSensors.cliff and Cliff.bottom?

**Comment by jakan2** [comment]
### CoreSensors.cliff

CoreSensors.cliff may be consist of three flags as below 

```
enum
{
  detectCliffAtRightSide = 0x01,
  detectCiffAtCenter = 0x02,
  detectCliffAtLeft = 0x04
}
```

So CoreSensors.cliff will be 0x03 when robot senses cliff at right side and center.

### cliff.bottom[]

While CoreSensors.cliff reflect the cliff detection result as flag, cliff.bottom[] store three bottom PSD sensor output.
cliff.bottom[0] --> right 
cliff.bottom[1] --> center
cliff.bottom[2] --> left

cliff.bottom[] to voltage would be calculated as 

```
int milli_voltage = 3300 * cliff.bottom[] / 2048;
```

http://robotics.ee.uwa.edu.au/courses/embedded/tutorials/tutorials/tutorial_8/Tutorial%208.htm is useful when you want to covert psd value to distance.

**Comment by yhju** [comment]
I think jakan2's answer is good enough.
