### ISSUE TITLE
Add interactive markers to our rviz

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#71]
Not sure what's necessary for this - whether we have to add code or just a rviz plugin. Ask marcus. But I'd like to be able to replicate one of their main tutorials:

http://ros.org/wiki/turtlebot_interactive_markers/Tutorials/UsingTurtlebotInteractiveMarkers

**Comment by bit-pirate** [comment]
That' s not a trival task. We probably need to get the whole turtlebot arm
navigation stack plus few extra packages working. Do we have a working
driver for our arm?
On Apr 16, 2012 8:07 AM, "Daniel Stonier" <
reply@reply.github.com>
wrote:

**Comment by bit-pirate** [comment]
Sorry, I have mistaken this for the interactive marker tools for turtlebot's arm. This one here is more simple.
