### ISSUE TITLE
Publish laptop battery status

### ISSUE THREAD

**Issue by corot** [yujinrobot/kobuki#72]
We are already publishing robot battery status in diagnostics, but not laptop data. TBD the format, according with the visualization tool we will use (maybe turtlebot dashboard, maybe our own app)

**Comment by stonier** [comment]
I'm fine with keeping the robot battery status simple (i.e. simple 3-4 level warning) for now. 

Laptop battery status as another diagnostic task in kobuki_node still needed though.

**Comment by stonier** [comment]
Let's make the laptop battery status generated by a separate program (not kobuki_node).

**Comment by yhju** [comment]
We can reuse a script at turtlebot_node/scripts/laptop_battery.py 
But some modification and generalisation is required.

Some laptop has /proc/acpi/battery/BAT0 and some other laptop has /proc/acpi/battery/BAT1
Even units of capacity may vary.
