### ISSUE TITLE
Check on start-up, if robot is turned on

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/kobuki#73]
Kobuki_node starts-up even if the robot is not switch on. Maybe this works, since the USB-to-serial convert is powered via USB? We should have a check, if the robot is turned on. If not, stop start-up or at least show a message.

**Comment by stonier** [comment]
Good point - I can set up a function watchdogging the stream in the driver to let the system know if there is a live connection or not.

**Comment by stonier** [comment]
Doing this now - but not just on startup, continuously via the diagnostics.
