### ISSUE TITLE
Document firmware download

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#77]
If we can get our new server quickly, document there...otherwise roswiki will do.

**Comment by stonier** [comment]
Documentation needs to go here: http://kobuki.yujinrobot.com/index.php/support/howtos/

**Comment by jakan2** [comment]
daniel

I made how-to page on kobuki (http://kobuki.yujinrobot.com/index.php?cID=159
)
How about it??? that is my first page, would you like to give some comments
on it.
I will add the more figures for the user.

2012/4/17 Daniel Stonier <
reply@reply.github.com

**Comment by stonier** [comment]
It's funny :) Very friendly english.

One good english piece of advice - don't use quick english in official documentation. e.g. fw -> firmware. Even small numbers like 1-10 should be written one to ten. Such 'lazy' english does not get very respected in official documents (teenagers may use on their sms though or 'devs' on their github issues!).
