### ISSUE TITLE
Sensor diagnostics

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#93]
Add good diagnostics for all our sensors.

**Comment by stonier** [comment]
Look at what the turtlebot does, at least implement much of what they have.

Then work out what more we want.

**Comment by corot** [comment]
We provide now the following diagnostics:
- robot-laptop link watchdog
- robot/laptop batteries status
- sensors: bumper, cliff, wheel drop, motor current, gyro
- input ports: analog, digital

In the tutorial http://www.ros.org/wiki/kobuki/Tutorials/Diagnostics we also explain how to use specific tests.

**Comment by corot** [comment]
I close the issue, but there's still things to do, so I opened a new one related (#133)
