### ISSUE TITLE
check why we need two unstable rosinstallers

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/kobuki#96]
why is there a separate rosinstaller for jenkins. remove if possible, otherwise we need to keep two installers updated ...

**Comment by stonier** [comment]
Ive no idea - wasn't that you who made the jenkins rosinstaller!?

**Comment by bit-pirate** [comment]
aiiishh, now - after jenkins build failer :-) - I remember. The unstable rosinstaller wants read/write access to the git repos it is checking out. Hence, we either need to add Jenkins to the developers list :-) or we keep on with two rosinstallers. I guess in the long run we need a "read-only" rosinstaller anyway, or will that case be handle by the debs?

**Comment by stonier** [comment]
Yeah, I think everything should be read only. At least, I try and do like that. 

Reason: even in yujin, not everyone is on each git account, but will often want to download the code (mr yes for robots for instance). So it's a good habit to have it read only, and then developers just set the remote-url --push. We have to start setting up a convenient git alias list.
